-- =====================================================================
-- 0207  A tie in the command walk is settled by the issuance sequence,
--       not the heap
-- =====================================================================
-- forces_recert = TRUE. Two twin bodies change (ottoq.ottoq_react_to_refusals,
-- twin.ottoq_sim_confirm_commands), one column is added, nothing is new.
-- A0 pins every body; A1 proves each rewritten body differs from its pin
-- in exactly the named ORDER BY fragments.
--
-- THE FINDING (round 20, pair 8, db/checks/0116)
-- ---------------------------------------------------------------------
-- busy_day/171717/24t FAILED at 17:27 UTC on 2026-09-06: the arms
-- (b8f98769 / ab7c7139) booted the same world (fp 92b02f8b, h_cal
-- 11a24626) and diverged at sim 11:30, vehicle 0d43459d. In that tick the
-- decide path issued two proceed_to_stall commands for that vehicle to the
-- same stall bc469f6a (NASH staging): one for gate intake, one carrying
-- new_state = staged_awaiting_service. Both were refused target_occupied.
-- ottoq.ottoq_react_to_refusals walks refused commands
--
--     ORDER BY issued_at, vehicle_id, command_type, payload->>'stall_id'
--
-- (the 0059 "run-stable tiebreak"), and those two rows are equal on all
-- four keys. Whichever the sort delivered first took the first free
-- stall (91ebbf41), the other took the next (765adddb); the confirm walk
-- then kept the 91ebbf41 command and superseded the other. Arm A's
-- surviving command was the staging one, so the vehicle became
-- staged_awaiting_service; arm B's was the intake one, so it kept
-- arrived_at_gate with a stall pointer. From tick 20 the stall choices,
-- decisions, bookings and events differ: h_cmd 5dd1816d vs e6cbbdeb,
-- h_dec, h_evt, h_bkg and endst all moved; h_nrg, h_prop, h_defr, h_cal
-- did not.
--
-- The order the sort delivered is physical row order, and refused rows
-- have been UPDATEd (status, reaction), so their physical order is
-- whatever free space the two arms found. It is not a function of the
-- run. Measured prevalence of the tie (same run, issued_at, vehicle,
-- command_type, refused stall; refused target_occupied or
-- resource_faulted): 12 groups across 8 of round 20's 18 arms
-- (314159/12t twice per arm, 171717/24t once, 424242/24t once) and
-- 15,089 groups in the ledger since 08-28. The arms agreed on eleven of
-- the twelve; agreement was luck.
--
-- twin.ottoq_sim_confirm_commands has the same shape one layer earlier
-- (0060): its duplicate ranking and its current-intent window end in
-- c.payload::text and c.command_id. command_id is gen_random_uuid(); the
-- payload text of a rerouted command carries reroute_after and booking
-- ids, also per-run random. Its confirm walk ends in
-- COALESCE(c.payload->>'stall_id','') with no further key.
--
-- WHAT CHANGES
-- ---------------------------------------------------------------------
--   1. ottoq_vehicle_commands.command_seq bigint GENERATED BY DEFAULT AS
--      IDENTITY. The decide path issues commands sequentially and
--      deterministically, so issuance order IS a function of the run;
--      the sequence records it. Existing rows are numbered in physical
--      order by the rewrite and carry no meaning; every row from 0207 on
--      is issuance order. Every emitter names its columns, so BY DEFAULT
--      is safe.
--   2. ottoq_react_to_refusals: ORDER BY ... payload->>'stall_id',
--      command_seq. Nothing else in the body moves.
--   3. ottoq_sim_confirm_commands: the duplicate ranking's payload::text,
--      command_id becomes command_seq ASC (oldest issued survives, which
--      is what the 0060 comment says it meant); the current-intent
--      window's payload::text DESC, command_id DESC becomes command_seq
--      DESC (newest issued is current intent, likewise); the confirm walk
--      gains command_seq as its last key.
--
-- WHAT THIS PREDICTS (round 21)
-- ---------------------------------------------------------------------
--   171717/24t passes with both arms equal. Columns whose runs carried a
--   tie group in round 20 (314159/12t, 171717/24t, 424242/24t) may move
--   ONCE, because the tie is now resolved by issuance order instead of by
--   the order the arms happened to share; 171717/12t, normal_day and
--   424242/12t carried no tie group and must not move. Any move on those
--   three is not this migration's.
-- =====================================================================

BEGIN;

CREATE TEMP TABLE pin_0207 ON COMMIT DROP AS
SELECT n.nspname || '.' || p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')' AS sig,
       md5(pg_get_functiondef(p.oid)) AS h, p.prosecdef
  FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
 WHERE n.nspname IN ('public','ottoq','twin') AND p.prokind IN ('f','p');

DO $pre$
DECLARE v_h text; v_n int;
BEGIN
  IF EXISTS (SELECT 1 FROM cron.job j WHERE j.jobname ~ '^r[0-9]+_')
     OR EXISTS (SELECT 1 FROM pg_stat_activity a
                 WHERE a.query ILIKE '%ottoq_determinism_pair%' AND a.pid <> pg_backend_pid() AND a.state <> 'idle') THEN
    RAISE EXCEPTION '0207 refused: a certification round is scheduled or in flight';
  END IF;
  IF EXISTS (SELECT 1 FROM public.ottoq_sim_runs WHERE status = 'running') THEN
    RAISE EXCEPTION '0207 refused: a sim run is running';
  END IF;
  SELECT h INTO v_h FROM pin_0207 WHERE sig = 'ottoq.ottoq_react_to_refusals(p_sim_run_id uuid, p_depot_id uuid, p_clock timestamp with time zone)';
  IF v_h IS DISTINCT FROM 'ea24d2ab0362beeacfc43a496cdff456' THEN
    RAISE EXCEPTION '0207 refused: ottoq_react_to_refusals is not the body this file was written against (md5 %)', v_h;
  END IF;
  SELECT h INTO v_h FROM pin_0207 WHERE sig = 'twin.ottoq_sim_confirm_commands(p_sim_run_id uuid, p_clock timestamp with time zone)';
  IF v_h IS DISTINCT FROM '2629067887ac3110a86e78313f5fa4a5' THEN
    RAISE EXCEPTION '0207 refused: ottoq_sim_confirm_commands is not the body this file was written against (md5 %)', v_h;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid = 'public.ottoq_vehicle_commands'::regclass AND attname = 'command_seq' AND NOT attisdropped) THEN
    RAISE EXCEPTION '0207 refused: command_seq already exists';
  END IF;
  -- the finding is on disk exactly as described: two refused proceed_to_stall
  -- commands, same vehicle, same tick, same refused stall, in BOTH arms of pair 8.
  SELECT count(*) INTO v_n FROM (
    SELECT c.sim_run_id FROM public.ottoq_vehicle_commands c
     WHERE c.sim_run_id IN ('b8f98769-5ae5-4ac8-9aff-f9fd38bd2e0e','ab7c7139-9330-47f8-876a-a7d1d22ed6ba')
       AND c.vehicle_id = '0d43459d-a82f-4d46-9579-43fc89feb981' AND c.issued_at = '2026-09-01 11:30:00+00'
       AND c.command_type = 'proceed_to_stall' AND c.status = 'refused' AND c.reason_code = 'target_occupied'
       AND c.payload->>'stall_id' = 'bc469f6a-edfd-46b9-b71f-be3d9e249c74'
     GROUP BY c.sim_run_id HAVING count(*) = 2) s;
  IF v_n <> 2 THEN
    RAISE EXCEPTION '0207 refused: the pair-8 tie fixture is not on disk as described (% arms carry it)', v_n;
  END IF;
  RAISE NOTICE '0207 pre: both bodies pinned, column absent, the tie fixture is on disk';
END $pre$;

-- ---------------------------------------------------------------------
-- 1. The issuance sequence.
-- ---------------------------------------------------------------------
ALTER TABLE public.ottoq_vehicle_commands ADD COLUMN command_seq bigint GENERATED BY DEFAULT AS IDENTITY;
COMMENT ON COLUMN public.ottoq_vehicle_commands.command_seq IS
  '0207: issuance order. The decide path issues commands sequentially and deterministically, so this is a function of the run and the last key of every walk that ties on (issued_at, vehicle, type, stall). Rows from before 0207 are numbered in physical order by the column rewrite and mean nothing.';

-- ---------------------------------------------------------------------
-- 2. The refusal walk, from the catalog. One fragment.
-- ---------------------------------------------------------------------
DO $react$
DECLARE v_def text; v_n int;
  v_old text := $f$ORDER BY issued_at, vehicle_id, command_type, payload->>'stall_id'$f$;
  v_new text := $f$ORDER BY issued_at, vehicle_id, command_type, payload->>'stall_id', command_seq   /* 0207 */$f$;
BEGIN
  v_def := pg_get_functiondef('ottoq.ottoq_react_to_refusals(uuid,uuid,timestamptz)'::regprocedure);
  IF md5(v_def) <> 'ea24d2ab0362beeacfc43a496cdff456' THEN RAISE EXCEPTION '0207 step 2: body moved between pin and rewrite'; END IF;
  v_n := (length(v_def) - length(replace(v_def, v_old, ''))) / length(v_old);
  IF v_n <> 1 THEN RAISE EXCEPTION '0207 step 2: fragment occurs % times', v_n; END IF;
  EXECUTE replace(v_def, v_old, v_new);
  RAISE NOTICE '0207 step 2: react_to_refusals orders by command_seq last';
END $react$;

-- ---------------------------------------------------------------------
-- 3. The confirm walk, from the catalog. Three fragments.
-- ---------------------------------------------------------------------
DO $confirm$
DECLARE v_def text; v_n int; i int;
  v_old text[] := ARRAY[
    $f$ORDER BY c.issued_at ASC, c.payload::text ASC, c.command_id ASC$f$,
    $f$ORDER BY c.issued_at DESC, c.command_type DESC, (c.payload->>'stall_id') DESC, c.payload::text DESC, c.command_id DESC$f$,
    $f$ORDER BY c.issued_at, c.vehicle_id, c.command_type, COALESCE(c.payload->>'stall_id','')$f$];
  v_new text[] := ARRAY[
    $f$ORDER BY c.issued_at ASC, c.command_seq ASC   /* 0207: issuance order; payload::text carried per-run ids */$f$,
    $f$ORDER BY c.issued_at DESC, c.command_type DESC, (c.payload->>'stall_id') DESC, c.command_seq DESC   /* 0207 */$f$,
    $f$ORDER BY c.issued_at, c.vehicle_id, c.command_type, COALESCE(c.payload->>'stall_id',''), c.command_seq   /* 0207 */$f$];
BEGIN
  v_def := pg_get_functiondef('twin.ottoq_sim_confirm_commands(uuid,timestamptz)'::regprocedure);
  IF md5(v_def) <> '2629067887ac3110a86e78313f5fa4a5' THEN RAISE EXCEPTION '0207 step 3: body moved between pin and rewrite'; END IF;
  FOR i IN 1..3 LOOP
    v_n := (length(v_def) - length(replace(v_def, v_old[i], ''))) / length(v_old[i]);
    IF v_n <> 1 THEN RAISE EXCEPTION '0207 step 3: fragment % occurs % times', i, v_n; END IF;
    v_def := replace(v_def, v_old[i], v_new[i]);
  END LOOP;
  EXECUTE v_def;
  RAISE NOTICE '0207 step 3: confirm_commands ranks, windows and walks by command_seq last';
END $confirm$;

-- ---------------------------------------------------------------------
-- ASSERTIONS
-- ---------------------------------------------------------------------
DO $assert$
DECLARE
  v_changed text[]; v_new text[]; v_def text; v_run uuid; v_veh uuid; v_pair jsonb;
  v_c1 uuid; v_c2 uuid; v_c3 uuid; v_seq bigint[]; v_by_seq uuid[]; v_by_text uuid[]; v_n bigint;
BEGIN
  -- ── A0. THE PIN.
  SELECT array_agg(a.sig ORDER BY a.sig) INTO v_changed
    FROM pin_0207 a
    JOIN (SELECT n.nspname || '.' || p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')' AS sig,
                 md5(pg_get_functiondef(p.oid)) AS h, p.prosecdef
            FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
           WHERE n.nspname IN ('public','ottoq','twin') AND p.prokind IN ('f','p')) b USING (sig)
   WHERE a.h <> b.h OR a.prosecdef <> b.prosecdef;
  IF v_changed IS DISTINCT FROM ARRAY[
       'ottoq.ottoq_react_to_refusals(p_sim_run_id uuid, p_depot_id uuid, p_clock timestamp with time zone)',
       'twin.ottoq_sim_confirm_commands(p_sim_run_id uuid, p_clock timestamp with time zone)'] THEN
    RAISE EXCEPTION '0207 A0 FAILED: function bodies changed = %', v_changed;
  END IF;
  SELECT array_agg(b.sig) INTO v_new
    FROM (SELECT n.nspname || '.' || p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')' AS sig
            FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
           WHERE n.nspname IN ('public','ottoq','twin') AND p.prokind IN ('f','p')) b
    LEFT JOIN pin_0207 a USING (sig) WHERE a.sig IS NULL;
  IF v_new IS NOT NULL THEN RAISE EXCEPTION '0207 A0 FAILED: new functions = %', v_new; END IF;
  RAISE NOTICE '0207 A0: pin holds; exactly two bodies changed, none new';

  -- ── A1. Reverse replacements restore both pins.
  v_def := pg_get_functiondef('ottoq.ottoq_react_to_refusals(uuid,uuid,timestamptz)'::regprocedure);
  v_def := replace(v_def, $f$ORDER BY issued_at, vehicle_id, command_type, payload->>'stall_id', command_seq   /* 0207 */$f$,
                          $f$ORDER BY issued_at, vehicle_id, command_type, payload->>'stall_id'$f$);
  IF md5(v_def) <> 'ea24d2ab0362beeacfc43a496cdff456' THEN RAISE EXCEPTION '0207 A1 FAILED: react_to_refusals differs outside the fragment'; END IF;
  v_def := pg_get_functiondef('twin.ottoq_sim_confirm_commands(uuid,timestamptz)'::regprocedure);
  v_def := replace(v_def, $f$ORDER BY c.issued_at ASC, c.command_seq ASC   /* 0207: issuance order; payload::text carried per-run ids */$f$,
                          $f$ORDER BY c.issued_at ASC, c.payload::text ASC, c.command_id ASC$f$);
  v_def := replace(v_def, $f$ORDER BY c.issued_at DESC, c.command_type DESC, (c.payload->>'stall_id') DESC, c.command_seq DESC   /* 0207 */$f$,
                          $f$ORDER BY c.issued_at DESC, c.command_type DESC, (c.payload->>'stall_id') DESC, c.payload::text DESC, c.command_id DESC$f$);
  v_def := replace(v_def, $f$ORDER BY c.issued_at, c.vehicle_id, c.command_type, COALESCE(c.payload->>'stall_id',''), c.command_seq   /* 0207 */$f$,
                          $f$ORDER BY c.issued_at, c.vehicle_id, c.command_type, COALESCE(c.payload->>'stall_id','')$f$);
  IF md5(v_def) <> '2629067887ac3110a86e78313f5fa4a5' THEN RAISE EXCEPTION '0207 A1 FAILED: confirm_commands differs outside the three fragments'; END IF;
  RAISE NOTICE '0207 A1: both bodies revert to their pins';

  -- ── A2. The column: identity, bigint, filled, unique.
  IF NOT EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid = 'public.ottoq_vehicle_commands'::regclass AND a.attname = 'command_seq'
                    AND a.atttypid = 'bigint'::regtype AND a.attnotnull AND a.attidentity = 'd') THEN
    RAISE EXCEPTION '0207 A2 FAILED: command_seq is not a NOT NULL bigint identity (by default) column';
  END IF;
  SELECT count(*) - count(DISTINCT command_seq) INTO v_n FROM public.ottoq_vehicle_commands;
  IF v_n <> 0 THEN RAISE EXCEPTION '0207 A2 FAILED: % duplicate command_seq values after the fill', v_n; END IF;
  RAISE NOTICE '0207 A2: command_seq identity, filled, unique';

  -- ── A3. THE ORDER IS NOW A FUNCTION OF ISSUANCE, AND THE OLD ONE WAS NOT.
  --        Three commands emitted in a rolled-back scope, identical on every 0059/0060
  --        key, with payload text that sorts AGAINST issuance order. The new keys
  --        return them in issuance order; the old keys return them in text order.
  SELECT r.sim_run_id INTO v_run FROM public.ottoq_sim_runs r
   WHERE r.depot_id = '11111111-1111-1111-1111-111111111111' AND r.status = 'completed'
   ORDER BY r.started_at DESC, r.sim_run_id DESC LIMIT 1;
  SELECT v.id INTO v_veh FROM public.vehicles v WHERE v.home_depot_id = '11111111-1111-1111-1111-111111111111' ORDER BY v.id LIMIT 1;
  BEGIN
    v_c1 := ottoq.ottoq_emit_vehicle_command(v_run, '11111111-1111-1111-1111-111111111111', v_veh, 'proceed_to_stall',
              jsonb_build_object('stall_id', 'bc469f6a-edfd-46b9-b71f-be3d9e249c74', 'probe', '0207', 'z', 'c'), '2026-09-01 23:59:00+00');
    v_c2 := ottoq.ottoq_emit_vehicle_command(v_run, '11111111-1111-1111-1111-111111111111', v_veh, 'proceed_to_stall',
              jsonb_build_object('stall_id', 'bc469f6a-edfd-46b9-b71f-be3d9e249c74', 'probe', '0207', 'z', 'b'), '2026-09-01 23:59:00+00');
    v_c3 := ottoq.ottoq_emit_vehicle_command(v_run, '11111111-1111-1111-1111-111111111111', v_veh, 'proceed_to_stall',
              jsonb_build_object('stall_id', 'bc469f6a-edfd-46b9-b71f-be3d9e249c74', 'probe', '0207', 'z', 'a'), '2026-09-01 23:59:00+00');
    SELECT array_agg(c.command_seq ORDER BY c.command_seq) INTO v_seq FROM public.ottoq_vehicle_commands c WHERE c.command_id IN (v_c1, v_c2, v_c3);
    SELECT array_agg(c.command_id ORDER BY c.issued_at, c.vehicle_id, c.command_type, c.payload->>'stall_id', c.command_seq) INTO v_by_seq
      FROM public.ottoq_vehicle_commands c WHERE c.command_id IN (v_c1, v_c2, v_c3);
    SELECT array_agg(c.command_id ORDER BY c.issued_at ASC, c.payload::text ASC, c.command_id ASC) INTO v_by_text
      FROM public.ottoq_vehicle_commands c WHERE c.command_id IN (v_c1, v_c2, v_c3);
    IF NOT (v_seq[1] < v_seq[2] AND v_seq[2] < v_seq[3]) THEN
      RAISE EXCEPTION '0207 A3 FAILED: command_seq is not monotonic in issuance order: %', v_seq;
    END IF;
    IF v_by_seq IS DISTINCT FROM ARRAY[v_c1, v_c2, v_c3] THEN
      RAISE EXCEPTION '0207 A3 FAILED: the new keys do not return issuance order';
    END IF;
    IF v_by_text = ARRAY[v_c1, v_c2, v_c3] THEN
      RAISE EXCEPTION '0207 A3 FAILED: the old keys returned issuance order for a payload built to reverse it; the probe cannot discriminate';
    END IF;
    RAISE EXCEPTION USING ERRCODE = 'P0207', MESSAGE = 'scope rollback';
  EXCEPTION WHEN SQLSTATE 'P0207' THEN NULL;
  END;
  IF EXISTS (SELECT 1 FROM public.ottoq_vehicle_commands c WHERE c.payload->>'probe' = '0207') THEN
    RAISE EXCEPTION '0207 A3 FAILED: probe commands survived their rollback';
  END IF;
  RAISE NOTICE '0207 A3: three tied commands: new keys give issuance order, old keys gave text order; rolled back';

  -- ── A4. LIVE. A six-tick grid pair still passes on everything it judges.
  v_pair := public.ottoq_determinism_pair(424242, 6, 'grid_smoke', 'aacd0bb0-2d02-d101-72cc-33f70e950bc8'::uuid,
                                          '2026-09-01 02:00:00+00'::timestamptz, 120);
  IF NOT COALESCE((v_pair->>'equal')::boolean, false) THEN
    RAISE EXCEPTION '0207 A4 FAILED: the grid pair did not pass (outcome %)', v_pair->>'outcome';
  END IF;
  RAISE NOTICE '0207 A4: grid pair % / % equal on every judged hash', left(v_pair->'arm_a'->>'run',8), left(v_pair->'arm_b'->>'run',8);
  RAISE NOTICE '0207: all assertions passed';
END $assert$;

INSERT INTO public.ottoq_cert_lineage (name, forces_recert, note, classified_at)
VALUES ('0207_a_tie_in_the_command_walk_is_settled_by_the_issuance_sequence_not_the_heap', TRUE,
  'Round-20 pair 8 (busy_day/171717/24t) failed: two refused proceed_to_stall commands for one vehicle in one tick to one stall '
  'tied on every key of the 0059 ORDER BY in ottoq_react_to_refusals, so physical row order chose which reroute survived, and the '
  'arms chose differently at sim 11:30 (vehicle 0d43459d). ottoq_vehicle_commands.command_seq (identity) records issuance order; '
  'react_to_refusals and the three walks in ottoq_sim_confirm_commands end in it (replacing payload::text and the random '
  'command_id in the 0060 window and ranking). Tie prevalence: 12 groups in round 20, 15,089 since 08-28. Prediction: 171717/24t '
  'passes; 314159/12t, 171717/24t and 424242/24t (tie groups in round 20) may move once; 171717/12t, normal_day and 424242/12t '
  'must not move.',
  now())
ON CONFLICT (name) DO UPDATE SET forces_recert=EXCLUDED.forces_recert, note=EXCLUDED.note, classified_at=EXCLUDED.classified_at;

COMMIT;
