"""Write edge-functions/ottoq-depot-v2/contract_schemas.ts from contract/schemas/*.json.

The v2 door validates every event against the contract's own schemas, so it ships them. Run this after any schema
change; contract/test_ottoq_contract.py fails while the two disagree.

    python3 contract/build_edge_schemas.py [--check]
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "edge-functions" / "ottoq-depot-v2" / "contract_schemas.ts"


def render() -> str:
    lines = [
        "// GENERATED by contract/build_edge_schemas.py from contract/schemas/*.json. Do not edit: change a schema and rerun",
        "// the script. contract/test_ottoq_contract.py fails while this file and the schemas disagree.",
        "export const CONTRACT_SCHEMAS: Record<string, unknown> = {",
    ]
    for path in sorted((HERE / "schemas").glob("*.json")):
        body = json.dumps(json.loads(path.read_text()), indent=2, ensure_ascii=False).replace("\n", "\n  ")
        lines.append(f"  {json.dumps(path.name)}: {body},")
    lines.append("};")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        ok = OUT.exists() and OUT.read_text() == text
        print("in sync" if ok else f"STALE: rerun python3 contract/build_edge_schemas.py ({OUT})")
        sys.exit(0 if ok else 1)
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(HERE.parent)} ({len(text)} bytes)")
