// GENERATED by contract/build_edge_schemas.py from contract/schemas/*.json. Do not edit: change a schema and rerun
// the script. contract/test_ottoq_contract.py fails while this file and the schemas disagree.
export const CONTRACT_SCHEMAS: Record<string, unknown> = {
  "capacity.offer.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://ottoyard.com/schemas/ottoq/contract/0.1/capacity.offer.json",
    "title": "com.ottoyard.capacity.offer (OTTO-Q to operator)",
    "description": "What the depot holds for this operator in a window, in coarse counts. It never carries another tenant's car ids, charge levels, ETAs or counts (README, rule 4), so the schema admits no vehicle field at all. Informational: no ack.",
    "type": "object",
    "required": [
      "window",
      "held_for_you"
    ],
    "properties": {
      "window": {
        "$ref": "defs.json#/$defs/window"
      },
      "held_for_you": {
        "type": "object",
        "minProperties": 1,
        "propertyNames": {
          "$ref": "defs.json#/$defs/stallType"
        },
        "additionalProperties": {
          "type": "integer",
          "minimum": 0,
          "maximum": 1000
        }
      },
      "charge_wait_band": {
        "description": "How long this operator's next arriving car would wait for a charger, in coarse bands. A band, not a position: a position is an exact count of the cars ahead of yours, and some of them are another tenant's (README, rule 4).",
        "enum": [
          "none",
          "under_15_min",
          "15_to_60_min",
          "over_60_min"
        ]
      }
    },
    "additionalProperties": false
  },
  "defs.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://ottoyard.com/schemas/ottoq/contract/0.1/defs.json",
    "title": "OTTO-Q depot contract 0.1: shared definitions",
    "$defs": {
      "uuid": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "timestamp": {
        "description": "RFC 3339 date-time with an explicit offset or Z.",
        "type": "string",
        "format": "date-time",
        "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,9})?(Z|[+-]\\d{2}:\\d{2})$"
      },
      "vehicleRef": {
        "description": "The operator's own reference for one of its vehicles. OTTO-Q resolves it only within the credential's fleet and depot; a reference outside them reads as not found.",
        "type": "string",
        "minLength": 1,
        "maxLength": 64,
        "pattern": "^[A-Za-z0-9._:-]+$"
      },
      "serviceCode": {
        "description": "A code from the depot's published operation catalog (service_cadence_policy.svc). The door refuses a code the depot does not publish.",
        "type": "string",
        "pattern": "^[a-z][a-z0-9_]{1,40}$"
      },
      "stallCode": {
        "type": "string",
        "minLength": 1,
        "maxLength": 32,
        "pattern": "^[A-Za-z0-9._-]+$"
      },
      "stallType": {
        "description": "The engine's stall types (the stall_type enum, read 2026-10-09). The twin depot has dcfc, l2, staging, wash_bay and service_bay.",
        "enum": [
          "dcfc",
          "l2",
          "staging",
          "wash_bay",
          "detail_bay",
          "service_bay",
          "parking",
          "safety"
        ]
      },
      "percent": {
        "type": "number",
        "minimum": 0,
        "maximum": 100
      },
      "severity": {
        "description": "The operator's own severity, not raw fault codes.",
        "enum": [
          "low",
          "medium",
          "high",
          "critical"
        ]
      },
      "window": {
        "type": "object",
        "required": [
          "start",
          "end"
        ],
        "properties": {
          "start": {
            "$ref": "#/$defs/timestamp"
          },
          "end": {
            "$ref": "#/$defs/timestamp"
          }
        },
        "additionalProperties": false
      },
      "ackReason": {
        "description": "Why a directive was not carried out. Closed: OTTO-Q re-plans differently for each.",
        "enum": [
          "occupied",
          "vehicle_unresponsive",
          "unsafe",
          "charger_fault",
          "vehicle_not_at_depot",
          "owner_override",
          "expired",
          "superseded",
          "other"
        ]
      },
      "directiveRef": {
        "type": "object",
        "required": [
          "directive_id",
          "version"
        ],
        "properties": {
          "directive_id": {
            "$ref": "#/$defs/uuid"
          },
          "version": {
            "type": "integer",
            "minimum": 1
          }
        },
        "additionalProperties": false
      },
      "directiveHeader": {
        "description": "Every directive carries these. A directive is a request the operator may refuse: no ack by ack_deadline means not done.",
        "type": "object",
        "required": [
          "directive_id",
          "version",
          "supersedes",
          "issued_at",
          "valid_from",
          "expires_at",
          "ack_deadline",
          "vehicle_ref"
        ],
        "properties": {
          "directive_id": {
            "$ref": "#/$defs/uuid"
          },
          "version": {
            "type": "integer",
            "minimum": 1
          },
          "supersedes": {
            "oneOf": [
              {
                "type": "null"
              },
              {
                "$ref": "#/$defs/directiveRef"
              }
            ]
          },
          "issued_at": {
            "$ref": "#/$defs/timestamp"
          },
          "valid_from": {
            "$ref": "#/$defs/timestamp"
          },
          "expires_at": {
            "$ref": "#/$defs/timestamp"
          },
          "ack_deadline": {
            "$ref": "#/$defs/timestamp"
          },
          "vehicle_ref": {
            "$ref": "#/$defs/vehicleRef"
          }
        }
      }
    }
  },
  "depot.arrival.intent.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://ottoyard.com/schemas/ottoq/contract/0.1/depot.arrival.intent.json",
    "title": "com.ottoyard.depot.arrival.intent (operator to OTTO-Q)",
    "description": "A car is coming home: when, with how much charge, what it needs, and when it must be ready. A later intent for the same car (higher intent_version) replaces the earlier one. charge_target_pct is the owner's target and may only come from the owner's credential; without it the owner's contract applies (100% today, CLAUDE.md rule 9). OTTO-Q never lowers it.",
    "type": "object",
    "required": [
      "eta",
      "intent_version"
    ],
    "properties": {
      "intent_version": {
        "type": "integer",
        "minimum": 1
      },
      "eta": {
        "$ref": "defs.json#/$defs/timestamp"
      },
      "eta_spread_s": {
        "description": "The operator's own uncertainty on eta, one standard deviation, seconds.",
        "type": "integer",
        "minimum": 0,
        "maximum": 86400
      },
      "predicted_soc_pct": {
        "$ref": "defs.json#/$defs/percent"
      },
      "services_needed": {
        "type": "array",
        "items": {
          "$ref": "defs.json#/$defs/serviceCode"
        },
        "uniqueItems": true,
        "maxItems": 32
      },
      "ready_by": {
        "$ref": "defs.json#/$defs/timestamp"
      },
      "charge_target_pct": {
        "$ref": "defs.json#/$defs/percent"
      }
    },
    "additionalProperties": false
  },
  "directive.ack.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://ottoyard.com/schemas/ottoq/contract/0.1/directive.ack.json",
    "title": "com.ottoyard.directive.ack (operator to OTTO-Q)",
    "description": "The operator's answer to one version of one directive. accepted means it will be carried out; rejected means the operator chose not to; unable means it could not. Anything but accepted carries a reason from the closed list, and OTTO-Q re-plans on it; 'other' also carries detail. No ack by the directive's ack_deadline reads as not done.",
    "type": "object",
    "required": [
      "directive_id",
      "directive_version",
      "disposition",
      "observed_at"
    ],
    "properties": {
      "directive_id": {
        "$ref": "defs.json#/$defs/uuid"
      },
      "directive_version": {
        "type": "integer",
        "minimum": 1
      },
      "disposition": {
        "enum": [
          "accepted",
          "rejected",
          "unable"
        ]
      },
      "reason": {
        "$ref": "defs.json#/$defs/ackReason"
      },
      "detail": {
        "type": "string",
        "maxLength": 500
      },
      "observed_at": {
        "$ref": "defs.json#/$defs/timestamp"
      }
    },
    "additionalProperties": false,
    "allOf": [
      {
        "description": "Anything but accepted names its reason; accepted names none.",
        "if": {
          "properties": {
            "disposition": {
              "const": "accepted"
            }
          }
        },
        "then": {
          "not": {
            "required": [
              "reason"
            ]
          }
        },
        "else": {
          "required": [
            "reason"
          ]
        }
      },
      {
        "description": "'other' says what happened: it is the reason a person reads, and the one that grows the list.",
        "if": {
          "required": [
            "reason"
          ],
          "properties": {
            "reason": {
              "const": "other"
            }
          }
        },
        "then": {
          "required": [
            "detail"
          ]
        }
      }
    ]
  },
  "directive.charge.plan.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://ottoyard.com/schemas/ottoq/contract/0.1/directive.charge.plan.json",
    "title": "com.ottoyard.directive.charge.plan (OTTO-Q to operator)",
    "description": "The charge the car will get at its charger. charging_schedule maps 1:1 onto an OCPP 2.0.1 ChargingProfile (purpose TxProfile, kind Absolute): start_schedule to startSchedule, charging_rate_unit to chargingRateUnit, periods[].start_period_s to chargingSchedulePeriod[].startPeriod, limit to limit, number_phases to numberPhases. OTTO-Q's charger back end sets it at the charger; nothing is sent to the car. target_soc_pct is the owner's target (CLAUDE.md rule 9: 100% unless the owner set less) and OTTO-Q never lowers it. Power reaches the site as a schedule, never as a real-time setpoint (ADAPTERS.md law 2).",
    "type": "object",
    "allOf": [
      {
        "$ref": "defs.json#/$defs/directiveHeader"
      }
    ],
    "required": [
      "stall_code",
      "target_soc_pct",
      "charging_schedule"
    ],
    "properties": {
      "directive_id": true,
      "version": true,
      "supersedes": true,
      "issued_at": true,
      "valid_from": true,
      "expires_at": true,
      "ack_deadline": true,
      "vehicle_ref": true,
      "stall_code": {
        "$ref": "defs.json#/$defs/stallCode"
      },
      "evse_id": {
        "description": "The charger's EVSE id where the operator knows it (OCPI style).",
        "type": "string",
        "maxLength": 48
      },
      "target_soc_pct": {
        "$ref": "defs.json#/$defs/percent"
      },
      "ready_by": {
        "description": "When the car must be ready, where the depot knows its due time. Absent otherwise.",
        "$ref": "defs.json#/$defs/timestamp"
      },
      "charging_schedule": {
        "type": "object",
        "required": [
          "start_schedule",
          "charging_rate_unit",
          "periods"
        ],
        "properties": {
          "start_schedule": {
            "$ref": "defs.json#/$defs/timestamp"
          },
          "charging_rate_unit": {
            "enum": [
              "W",
              "A"
            ]
          },
          "periods": {
            "type": "array",
            "minItems": 1,
            "maxItems": 96,
            "items": {
              "type": "object",
              "required": [
                "start_period_s",
                "limit"
              ],
              "properties": {
                "start_period_s": {
                  "type": "integer",
                  "minimum": 0
                },
                "limit": {
                  "type": "number",
                  "minimum": 0
                },
                "number_phases": {
                  "type": "integer",
                  "minimum": 1,
                  "maximum": 3
                }
              },
              "additionalProperties": false
            }
          }
        },
        "additionalProperties": false
      }
    },
    "additionalProperties": false
  },
  "directive.service.schedule.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://ottoyard.com/schemas/ottoq/contract/0.1/directive.service.schedule.json",
    "title": "com.ottoyard.directive.service.schedule (OTTO-Q to operator)",
    "description": "The services the car will get on this visit, where and when. Operations whose windows overlap run concurrently (a sensor clean during a charge). Every service the depot found the car to need is on it: no car leaves with one open (CLAUDE.md rule 9).",
    "type": "object",
    "allOf": [
      {
        "$ref": "defs.json#/$defs/directiveHeader"
      }
    ],
    "required": [
      "operations"
    ],
    "properties": {
      "directive_id": true,
      "version": true,
      "supersedes": true,
      "issued_at": true,
      "valid_from": true,
      "expires_at": true,
      "ack_deadline": true,
      "vehicle_ref": true,
      "operations": {
        "type": "array",
        "minItems": 1,
        "maxItems": 32,
        "items": {
          "type": "object",
          "required": [
            "service_code",
            "window"
          ],
          "properties": {
            "service_code": {
              "$ref": "defs.json#/$defs/serviceCode"
            },
            "stall_code": {
              "$ref": "defs.json#/$defs/stallCode"
            },
            "window": {
              "$ref": "defs.json#/$defs/window"
            }
          },
          "additionalProperties": false
        }
      }
    },
    "additionalProperties": false
  },
  "directive.stall.assignment.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://ottoyard.com/schemas/ottoq/contract/0.1/directive.stall.assignment.json",
    "title": "com.ottoyard.directive.stall.assignment (OTTO-Q to operator)",
    "description": "Where the car should go and for how long. A request, not a command to the car: the operator moves it or answers why not.",
    "type": "object",
    "allOf": [
      {
        "$ref": "defs.json#/$defs/directiveHeader"
      }
    ],
    "required": [
      "stall",
      "purpose",
      "window"
    ],
    "properties": {
      "directive_id": true,
      "version": true,
      "supersedes": true,
      "issued_at": true,
      "valid_from": true,
      "expires_at": true,
      "ack_deadline": true,
      "vehicle_ref": true,
      "stall": {
        "type": "object",
        "required": [
          "stall_code",
          "stall_type"
        ],
        "properties": {
          "stall_code": {
            "$ref": "defs.json#/$defs/stallCode"
          },
          "stall_type": {
            "$ref": "defs.json#/$defs/stallType"
          },
          "zone": {
            "type": "string",
            "maxLength": 32
          }
        },
        "additionalProperties": false
      },
      "purpose": {
        "enum": [
          "charge",
          "service",
          "staging",
          "hold"
        ]
      },
      "window": {
        "$ref": "defs.json#/$defs/window"
      }
    },
    "additionalProperties": false
  },
  "envelope.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://ottoyard.com/schemas/ottoq/contract/0.1/envelope.json",
    "title": "OTTO-Q depot contract 0.1: the envelope",
    "description": "A CloudEvents 1.0.2 event in structured JSON mode, narrowed by this contract. There is no tenant, depot or data-source attribute: those come from the credential. Unknown attributes are refused.",
    "type": "object",
    "required": [
      "specversion",
      "id",
      "source",
      "type",
      "time",
      "datacontenttype",
      "dataschema",
      "data"
    ],
    "properties": {
      "specversion": {
        "const": "1.0"
      },
      "id": {
        "type": "string",
        "minLength": 1,
        "maxLength": 128
      },
      "source": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256
      },
      "type": {
        "enum": [
          "com.ottoyard.vehicle.telemetry",
          "com.ottoyard.depot.arrival.intent",
          "com.ottoyard.vehicle.fault.summary",
          "com.ottoyard.vehicle.departed",
          "com.ottoyard.directive.ack",
          "com.ottoyard.directive.stall.assignment",
          "com.ottoyard.directive.charge.plan",
          "com.ottoyard.directive.service.schedule",
          "com.ottoyard.readiness.forecast",
          "com.ottoyard.capacity.offer"
        ]
      },
      "time": {
        "description": "When the occurrence happened (CloudEvents time), kept as sent. Required here although optional in CloudEvents.",
        "$ref": "defs.json#/$defs/timestamp"
      },
      "datacontenttype": {
        "const": "application/json"
      },
      "dataschema": {
        "type": "string",
        "format": "uri"
      },
      "subject": {
        "type": "string",
        "minLength": 1,
        "maxLength": 128
      },
      "sequence": {
        "description": "CloudEvents sequence extension: the event's place in its source's stream, compared lexicographically. Zero-padded to 20 digits so that order is numeric order.",
        "type": "string",
        "pattern": "^[0-9]{20}$"
      },
      "ottoqsig": {
        "description": "Extension attribute: a detached JWS (RFC 7515 Appendix F, compact form, alg Ed25519 per RFC 9864) whose payload is the RFC 8785 canonical form of this whole event without ottoqsig itself, so the signature binds id, source, type, subject, time and data together. Carried by everything OTTO-Q sends (README, Signatures).",
        "type": "string",
        "pattern": "^[A-Za-z0-9_-]+\\.\\.[A-Za-z0-9_-]+$"
      },
      "data": {
        "type": "object"
      }
    },
    "additionalProperties": false,
    "allOf": [
      {
        "description": "Everything an operator sends concerns one vehicle, is ordered per vehicle, and names the vehicle in its source (the sequence extension's own advice for a per-subject order).",
        "if": {
          "properties": {
            "type": {
              "enum": [
                "com.ottoyard.vehicle.telemetry",
                "com.ottoyard.depot.arrival.intent",
                "com.ottoyard.vehicle.fault.summary",
                "com.ottoyard.vehicle.departed",
                "com.ottoyard.directive.ack"
              ]
            }
          }
        },
        "then": {
          "required": [
            "subject",
            "sequence"
          ],
          "properties": {
            "source": {
              "pattern": "^urn:ottoq:src:[a-z0-9][a-z0-9_.-]{0,62}:[A-Za-z0-9._:-]{1,64}$"
            },
            "subject": {
              "$ref": "defs.json#/$defs/vehicleRef"
            },
            "ottoqsig": false
          }
        }
      },
      {
        "description": "Everything OTTO-Q sends is signed and names its depot as the source.",
        "if": {
          "properties": {
            "type": {
              "enum": [
                "com.ottoyard.directive.stall.assignment",
                "com.ottoyard.directive.charge.plan",
                "com.ottoyard.directive.service.schedule",
                "com.ottoyard.readiness.forecast",
                "com.ottoyard.capacity.offer"
              ]
            }
          }
        },
        "then": {
          "required": [
            "ottoqsig"
          ],
          "properties": {
            "source": {
              "pattern": "^urn:ottoq:depot:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
            },
            "sequence": true
          }
        }
      },
      {
        "if": {
          "properties": {
            "type": {
              "const": "com.ottoyard.vehicle.telemetry"
            }
          }
        },
        "then": {
          "properties": {
            "dataschema": {
              "const": "https://ottoyard.com/schemas/ottoq/contract/0.1/vehicle.telemetry.json"
            },
            "data": {
              "$ref": "vehicle.telemetry.json"
            }
          }
        }
      },
      {
        "if": {
          "properties": {
            "type": {
              "const": "com.ottoyard.depot.arrival.intent"
            }
          }
        },
        "then": {
          "properties": {
            "dataschema": {
              "const": "https://ottoyard.com/schemas/ottoq/contract/0.1/depot.arrival.intent.json"
            },
            "data": {
              "$ref": "depot.arrival.intent.json"
            }
          }
        }
      },
      {
        "if": {
          "properties": {
            "type": {
              "const": "com.ottoyard.vehicle.fault.summary"
            }
          }
        },
        "then": {
          "properties": {
            "dataschema": {
              "const": "https://ottoyard.com/schemas/ottoq/contract/0.1/vehicle.fault.summary.json"
            },
            "data": {
              "$ref": "vehicle.fault.summary.json"
            }
          }
        }
      },
      {
        "if": {
          "properties": {
            "type": {
              "const": "com.ottoyard.vehicle.departed"
            }
          }
        },
        "then": {
          "properties": {
            "dataschema": {
              "const": "https://ottoyard.com/schemas/ottoq/contract/0.1/vehicle.departed.json"
            },
            "data": {
              "$ref": "vehicle.departed.json"
            }
          }
        }
      },
      {
        "if": {
          "properties": {
            "type": {
              "const": "com.ottoyard.directive.ack"
            }
          }
        },
        "then": {
          "properties": {
            "dataschema": {
              "const": "https://ottoyard.com/schemas/ottoq/contract/0.1/directive.ack.json"
            },
            "data": {
              "$ref": "directive.ack.json"
            }
          }
        }
      },
      {
        "if": {
          "properties": {
            "type": {
              "const": "com.ottoyard.directive.stall.assignment"
            }
          }
        },
        "then": {
          "properties": {
            "dataschema": {
              "const": "https://ottoyard.com/schemas/ottoq/contract/0.1/directive.stall.assignment.json"
            },
            "data": {
              "$ref": "directive.stall.assignment.json"
            }
          }
        }
      },
      {
        "if": {
          "properties": {
            "type": {
              "const": "com.ottoyard.directive.charge.plan"
            }
          }
        },
        "then": {
          "properties": {
            "dataschema": {
              "const": "https://ottoyard.com/schemas/ottoq/contract/0.1/directive.charge.plan.json"
            },
            "data": {
              "$ref": "directive.charge.plan.json"
            }
          }
        }
      },
      {
        "if": {
          "properties": {
            "type": {
              "const": "com.ottoyard.directive.service.schedule"
            }
          }
        },
        "then": {
          "properties": {
            "dataschema": {
              "const": "https://ottoyard.com/schemas/ottoq/contract/0.1/directive.service.schedule.json"
            },
            "data": {
              "$ref": "directive.service.schedule.json"
            }
          }
        }
      },
      {
        "if": {
          "properties": {
            "type": {
              "const": "com.ottoyard.readiness.forecast"
            }
          }
        },
        "then": {
          "properties": {
            "dataschema": {
              "const": "https://ottoyard.com/schemas/ottoq/contract/0.1/readiness.forecast.json"
            },
            "data": {
              "$ref": "readiness.forecast.json"
            }
          }
        }
      },
      {
        "if": {
          "properties": {
            "type": {
              "const": "com.ottoyard.capacity.offer"
            }
          }
        },
        "then": {
          "properties": {
            "dataschema": {
              "const": "https://ottoyard.com/schemas/ottoq/contract/0.1/capacity.offer.json"
            },
            "data": {
              "$ref": "capacity.offer.json"
            }
          }
        }
      }
    ]
  },
  "readiness.forecast.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://ottoyard.com/schemas/ottoq/contract/0.1/readiness.forecast.json",
    "title": "com.ottoyard.readiness.forecast (OTTO-Q to operator)",
    "description": "When OTTO-Q expects the car to be ready for work, with its spread. Informational: no ack.",
    "type": "object",
    "required": [
      "vehicle_ref",
      "as_of",
      "ready_p50",
      "ready_p90",
      "open_services"
    ],
    "properties": {
      "vehicle_ref": {
        "$ref": "defs.json#/$defs/vehicleRef"
      },
      "as_of": {
        "$ref": "defs.json#/$defs/timestamp"
      },
      "ready_p50": {
        "$ref": "defs.json#/$defs/timestamp"
      },
      "ready_p90": {
        "$ref": "defs.json#/$defs/timestamp"
      },
      "soc_at_ready_pct": {
        "$ref": "defs.json#/$defs/percent"
      },
      "open_services": {
        "type": "array",
        "items": {
          "$ref": "defs.json#/$defs/serviceCode"
        },
        "uniqueItems": true,
        "maxItems": 32
      }
    },
    "additionalProperties": false
  },
  "vehicle.departed.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://ottoyard.com/schemas/ottoq/contract/0.1/vehicle.departed.json",
    "title": "com.ottoyard.vehicle.departed (operator to OTTO-Q)",
    "description": "The car has left the depot. OTTO-Q releases what it held for the car; it never learns the car's mission.",
    "type": "object",
    "required": [
      "departed_at",
      "reason"
    ],
    "properties": {
      "departed_at": {
        "$ref": "defs.json#/$defs/timestamp"
      },
      "reason": {
        "enum": [
          "dispatched",
          "owner_recall",
          "towed",
          "other"
        ]
      },
      "soc_pct": {
        "$ref": "defs.json#/$defs/percent"
      }
    },
    "additionalProperties": false
  },
  "vehicle.fault.summary.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://ottoyard.com/schemas/ottoq/contract/0.1/vehicle.fault.summary.json",
    "title": "com.ottoyard.vehicle.fault.summary (operator to OTTO-Q)",
    "description": "The operator's own reading of a fault: its severity and category. Raw codes may ride along in fault_codes and are never interpreted. takes_vehicle_offline is the one signal that lets OTTO-Q end a charge short or route the car straight to a service stall or long-term staging (CLAUDE.md rule 9).",
    "type": "object",
    "required": [
      "severity",
      "category"
    ],
    "properties": {
      "severity": {
        "$ref": "defs.json#/$defs/severity"
      },
      "category": {
        "enum": [
          "vehicle_damage",
          "vehicle_malfunction",
          "sensor_anomaly",
          "tire_issue",
          "excessive_contamination",
          "vehicle_unresponsive",
          "safety_concern",
          "other"
        ]
      },
      "description": {
        "type": "string",
        "maxLength": 500
      },
      "services_needed": {
        "type": "array",
        "items": {
          "$ref": "defs.json#/$defs/serviceCode"
        },
        "uniqueItems": true,
        "maxItems": 16
      },
      "takes_vehicle_offline": {
        "type": "boolean"
      },
      "fault_codes": {
        "description": "The operator's own fault codes, proprietary or OBD-II, stored as sent and never interpreted: OTTO-Q acts on severity, category, services_needed and takes_vehicle_offline.",
        "type": "array",
        "items": {
          "type": "string",
          "pattern": "^[A-Za-z0-9._:-]{1,32}$"
        },
        "uniqueItems": true,
        "maxItems": 64
      }
    },
    "additionalProperties": false
  },
  "vehicle.telemetry.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://ottoyard.com/schemas/ottoq/contract/0.1/vehicle.telemetry.json",
    "title": "com.ottoyard.vehicle.telemetry (operator to OTTO-Q)",
    "description": "Vehicle signals named by their COVESA VSS 6.0 path, each with the time it was observed. Units are VSS units. A signal older than its time to live reads as unknown (README, rule 2). The vehicle's depot state is not sent: OTTO-Q derives it. Precise location is accepted only inside the depot geofence (rule 5).",
    "type": "object",
    "required": [
      "signals"
    ],
    "properties": {
      "signals": {
        "type": "object",
        "minProperties": 1,
        "properties": {
          "Vehicle.Powertrain.TractionBattery.StateOfCharge.Current": {
            "$ref": "#/$defs/percentSignal"
          },
          "Vehicle.Powertrain.TractionBattery.StateOfCharge.Displayed": {
            "$ref": "#/$defs/percentSignal"
          },
          "Vehicle.Powertrain.TractionBattery.Temperature.Average": {
            "$ref": "#/$defs/numberSignal"
          },
          "Vehicle.Powertrain.TractionBattery.Range": {
            "$ref": "#/$defs/uintSignal"
          },
          "Vehicle.Powertrain.Range": {
            "$ref": "#/$defs/uintSignal"
          },
          "Vehicle.Powertrain.TractionBattery.StateOfHealth": {
            "$ref": "#/$defs/percentSignal"
          },
          "Vehicle.Powertrain.TractionBattery.CurrentPower": {
            "$ref": "#/$defs/numberSignal"
          },
          "Vehicle.Powertrain.TractionBattery.NetCapacity": {
            "$ref": "#/$defs/uint16Signal"
          },
          "Vehicle.Powertrain.TractionBattery.Charging.IsCharging": {
            "$ref": "#/$defs/boolSignal"
          },
          "Vehicle.Powertrain.TractionBattery.Charging.ChargeLimit": {
            "$ref": "#/$defs/wholePercentSignal"
          },
          "Vehicle.Powertrain.TractionBattery.Charging.TimeToComplete": {
            "$ref": "#/$defs/uintSignal"
          },
          "Vehicle.Speed": {
            "$ref": "#/$defs/numberSignal"
          },
          "Vehicle.TraveledDistance": {
            "$ref": "#/$defs/uintSignal"
          },
          "Vehicle.CurrentLocation.Latitude": {
            "$ref": "#/$defs/latitudeSignal"
          },
          "Vehicle.CurrentLocation.Longitude": {
            "$ref": "#/$defs/longitudeSignal"
          },
          "Vehicle.Diagnostics.DTCList": {
            "$ref": "#/$defs/dtcSignal"
          },
          "Vehicle.Exterior.AirTemperature": {
            "$ref": "#/$defs/numberSignal"
          },
          "Vehicle.Chassis.Axle.Row1.Wheel.Left.Tire.Pressure": {
            "$ref": "#/$defs/kpaSignal"
          },
          "Vehicle.Chassis.Axle.Row1.Wheel.Right.Tire.Pressure": {
            "$ref": "#/$defs/kpaSignal"
          },
          "Vehicle.Chassis.Axle.Row2.Wheel.Left.Tire.Pressure": {
            "$ref": "#/$defs/kpaSignal"
          },
          "Vehicle.Chassis.Axle.Row2.Wheel.Right.Tire.Pressure": {
            "$ref": "#/$defs/kpaSignal"
          }
        },
        "additionalProperties": false,
        "dependentRequired": {
          "Vehicle.CurrentLocation.Latitude": [
            "Vehicle.CurrentLocation.Longitude"
          ],
          "Vehicle.CurrentLocation.Longitude": [
            "Vehicle.CurrentLocation.Latitude"
          ]
        }
      }
    },
    "additionalProperties": false,
    "$defs": {
      "ts": {
        "$ref": "defs.json#/$defs/timestamp"
      },
      "percentSignal": {
        "type": "object",
        "required": [
          "value",
          "ts"
        ],
        "additionalProperties": false,
        "properties": {
          "value": {
            "$ref": "defs.json#/$defs/percent"
          },
          "ts": {
            "$ref": "#/$defs/ts"
          }
        }
      },
      "wholePercentSignal": {
        "description": "A whole-number percent (VSS uint8).",
        "type": "object",
        "required": [
          "value",
          "ts"
        ],
        "additionalProperties": false,
        "properties": {
          "value": {
            "type": "integer",
            "minimum": 0,
            "maximum": 100
          },
          "ts": {
            "$ref": "#/$defs/ts"
          }
        }
      },
      "numberSignal": {
        "type": "object",
        "required": [
          "value",
          "ts"
        ],
        "additionalProperties": false,
        "properties": {
          "value": {
            "type": "number"
          },
          "ts": {
            "$ref": "#/$defs/ts"
          }
        }
      },
      "uintSignal": {
        "type": "object",
        "required": [
          "value",
          "ts"
        ],
        "additionalProperties": false,
        "properties": {
          "value": {
            "type": "integer",
            "minimum": 0,
            "maximum": 4294967295
          },
          "ts": {
            "$ref": "#/$defs/ts"
          }
        }
      },
      "uint16Signal": {
        "type": "object",
        "required": [
          "value",
          "ts"
        ],
        "additionalProperties": false,
        "properties": {
          "value": {
            "type": "integer",
            "minimum": 0,
            "maximum": 65535
          },
          "ts": {
            "$ref": "#/$defs/ts"
          }
        }
      },
      "kpaSignal": {
        "type": "object",
        "required": [
          "value",
          "ts"
        ],
        "additionalProperties": false,
        "properties": {
          "value": {
            "type": "integer",
            "minimum": 0,
            "maximum": 1000
          },
          "ts": {
            "$ref": "#/$defs/ts"
          }
        }
      },
      "boolSignal": {
        "type": "object",
        "required": [
          "value",
          "ts"
        ],
        "additionalProperties": false,
        "properties": {
          "value": {
            "type": "boolean"
          },
          "ts": {
            "$ref": "#/$defs/ts"
          }
        }
      },
      "latitudeSignal": {
        "type": "object",
        "required": [
          "value",
          "ts"
        ],
        "additionalProperties": false,
        "properties": {
          "value": {
            "type": "number",
            "minimum": -90,
            "maximum": 90
          },
          "ts": {
            "$ref": "#/$defs/ts"
          }
        }
      },
      "longitudeSignal": {
        "type": "object",
        "required": [
          "value",
          "ts"
        ],
        "additionalProperties": false,
        "properties": {
          "value": {
            "type": "number",
            "minimum": -180,
            "maximum": 180
          },
          "ts": {
            "$ref": "#/$defs/ts"
          }
        }
      },
      "dtcSignal": {
        "type": "object",
        "required": [
          "value",
          "ts"
        ],
        "additionalProperties": false,
        "properties": {
          "value": {
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^[PCBU][0-9A-F]{4,6}$"
            },
            "maxItems": 64,
            "uniqueItems": true
          },
          "ts": {
            "$ref": "#/$defs/ts"
          }
        }
      }
    }
  },
};
