-- ============================================================================================
-- 0046 — SAME-SEED DETERMINISM ARMS: run the identical world twice; the ledgers must match.
--
-- Chase's repeatability complaint ("very little if any repeatability"), made executable.
-- The claim under test decomposes into two properties:
--   (a) same seed => same INITIAL world (fleet state, wear, cadence, emission gates)
--   (b) same initial world => same EVOLUTION (the 0054/0060 ordering work's territory)
-- A pair that diverges says at least one is false; a triplet says which way it drifts.
--
-- ── VERDICT, first triplet (2026-08-29) — FAIL, with structure ─────────────────────────────
-- Three arms, byte-identical treatment each time:
--   reset:  ottoq_tick_invariance_reset_fleet(depot 11111111, seed 424242)
--   start:  twin.ottoq_sim_start_run('busy_day', '2026-09-01 02:00:00+00', 60, 424242,
--           'cert_harness');  prime_deployment(clock, 0.70);  12 synchronous ticks to 08:00.
--
--   arm | run_id                               | cmds | decisions | events | bookings
--   A   | e8852600-1e8d-4f2c-af92-88dcb46d4ad4 |  507 |      1426 |   3236 |      810
--   B   | c1ca08bb-e91b-4986-a97a-9c4e72e875dc |  526 |      1506 |   3007 |      788
--   C   | de027539-8f2b-4478-978a-cb8eef3a4c5c |  587 |      1698 |    785 |      798
--   All four stream hashes differ on every pair. No arm matches any other.
--
-- TWO DISTINCT BLEEDS, both cross-run state the seeded reset does not cover:
--   1. SCHEDULING DRIFT, monotonic across arms: wash_atoms 84→73→64, soil_index_mean
--      .0381→.0408→.0416, kwh_per_100km 24.06→20.26→13.95, refusal_escalated 134→139→209.
--      Monotonic = cumulative per-vehicle state (wear/soil/cadence/need history) carried
--      between runs. reset_fleet restores SoC/state/stalls/cycles_since_wash only; the
--      harness start path (twin.ottoq_sim_start_run) does NOT re-draw need profiles or
--      re-phase wear the way ottoq_sim_run_scenario's boot does.
--   2. EMISSION SUPPRESSION, cliff-shaped in arm C: vehicle.state_changed 1566→1422→30,
--      stall.state_changed 844→798→0 — while activity continued (58 charge sessions started,
--      116 dispatches completed).
--      ROOT-CAUSED (same day, superseding the flood-guard suspicion this file first recorded):
--      not suppression — MIS-TAGGING. ottoq_active_sim_run_id() cached 'none' in its
--      transaction-scoped GUC when the arm's fleet reset fired triggers before the run row
--      existed, and arm C ran reset+start+ticks in ONE transaction — so 12 ticks of witness
--      events were written sim_run_id NULL / data_source 'production' (arms A/B ticked in a
--      separate transaction and resolved correctly; that procedural difference was the cliff).
--      The same mechanism mis-tagged EVERY run teardown ever: stop flips status before the
--      depot reset, so teardown events found no 'running' run — 4,074 orphaned witness rows
--      measured in one 16-minute window. Fixed by 0092 (no cached misses; GUC pinned at run
--      start and at teardown); check 0045 R12 watches the teardown window permanently.
--
-- ── SECOND PAIR, after 0092–0096 (2026-08-29, arms 05553150 / e1fe726c) ────────────────────
-- Property (a) is now PROVEN: both arms stamped the SAME world fingerprint
-- (3c903a8f2e7dc924ca2a6661f62feb21) — the 0095 whitelist reset + 0093 residue strip close
-- the world completely (rolled-back 8-tick probe: fp_equal=t, zero column diffs).
--
-- Property (b) FAILS, and the first divergence names its mechanisms. Tick 1 is BYTE-IDENTICAL
-- (55 commands, same hash). Divergence begins at tick 2: five 'stage' (ready:true) commands
-- present in arm A, absent in arm B — the task_start staging decision drew differently from
-- an identical world. Two wall-clock/cross-run inputs reach that decision:
--   1. PROPOSAL TTLs LIVE IN THE WALL DOMAIN: greedy proposals get expires_at = now()+120
--      REAL seconds and ottoq_l2_external_proposal filters >= now() — ticks run at variable
--      wall speed, so a proposal straddles the next tick in one arm and is expired in the
--      other (20 proposals in arm A vs 32 in arm B). Same disease class as the 0067
--      reservation-expiry fix; the cure is the same: sim-domain freshness for sim runs.
--   2. ottoq_ops_approvals IS READ WITHOUT RUN SCOPE: the table HAS sim_run_id, but decide's
--      checks filter only vehicle/type/status/created_at — so arm B inherits arm A's
--      approvals (66 approvals written during the pair; 271 accumulated). One run's
--      greenlights leak into the next run's gates.
-- Fix both, then re-run this pair expecting equality tick by tick; the first-divergence
-- bisection above is the debugging loop to repeat if a third mechanism hides behind them.
--
-- ── PAIRS 4 AND 5, after 0097/0098 (2026-08-29) — the horizon moves, the diagnosis lands ──
-- Pair 4 (02ad9218/40cd6a63, after 0097 expired approvals at teardown): ticks 1 AND 2 now
-- byte-identical — mechanism 2 (approvals) confirmed dead. Divergence moved to tick 3:
-- one vehicle (bc55d859) admitted to the overnight drain in one arm only. Root: the
-- admission cursor ORDER BY (deferred count DESC, last_state_change) LIMIT n — same-tick
-- transitions share last_state_change (the sim clock), so the last slot went in heap order.
-- Fixed by 0098 (append id).
-- Pair 5 (908c16bc/de282fc7, after 0098): stall_assignment queue identical through
-- position 28 (the drain fix held); the first divergence is now a forward temp-hold at
-- tick 2 — the same window's hold on stall a06d087f went to fixture vehicle a1111111 in
-- arm A and b2222222 in arm B, and the pairing permutation cascades from there.
--
-- ── THE GENERAL DIAGNOSIS (ending one-at-a-time whack-a-mole) ─────────────────────────────
-- A live sweep of pg_proc for `ORDER BY ... LIMIT` cursors lacking a closing unique key
-- found DOZENS of sites across the tick path, dominated by two families:
--   * `ORDER BY vn.created_at DESC LIMIT 1` — "the latest need" picked by a WALL-clock
--     column whose values tie for rows created in the same transaction (arrival_disposition,
--     book_appointment, decide_wash_triage, plan_opportunistic_charges, readmit_*,
--     record_enacted_booking, reoptimize_reservation_book, reserve_inbound_bays, ...);
--   * score-only ORDER BY with no id tiebreak (the 0054/0067 disease, re-grown since the
--     decide-path rewrite).
-- The remaining work is a 0054-scale sweep: enumerate every site from the live catalog,
-- close each order with the row's unique key, one self-verifying migration, then re-run
-- this pair expecting tick-by-tick equality. The sweep query lives in the session notes;
-- rebuild it as: regexp over pg_proc.prosrc for 'ORDER BY ... LIMIT' minus snippets already
-- carrying id/stall_code/seq columns.
--
-- ── PAIR 6, after 0099 swept the created_at family (2026-08-29, arms b2148f8b/2dc7d9df) ────
-- 0099 closed the 12 `ORDER BY created_at DESC LIMIT 1` latest-need cursors across 10
-- functions with the run-stable `visit_key` tiebreak (visit_key = vehicle:sim-time — a per-run
-- random uuid would NOT do; 0054's rule). Pair 6: tick 2's forward-hold divergence is GONE
-- (ticks 1–2 identical for the third pair running); tick 3's first divergence moved one hold
-- upstream again — vehicle 03726c33's same-tick 5-minute temp_hold landed on stall 06acce00
-- in arm A and 9b1306c1 in arm B, and vehicle 77ecd026's gate intake cascaded from that.
-- FRONT: the same-tick HOLD-BOOKING LOOPS (which vehicle's hold books first / which candidate
-- survives). Next: enumerate the remaining score-only ORDER BY ... LIMIT sites from the sweep
-- (svc_to_stall_type and the tail past the first 40) plus the loops that call
-- book_hold_stall in the twin phase, close each, re-pair. The convergence trend across pairs
-- 3→6 (divergence at tick 2 pos ~1 → tick 3 pos 21 → pos 29 → pos 28-with-fewer-diffs) says
-- the method is working; what remains is finishing the enumeration, not new theory.
--
-- ── PAIR 7, after 0100 closed the service-flow admissions (arms 2ebf111d/4f203026) ────────
-- Command and decision COUNTS are now equal (655/655, 1854/1854) — pure permutation remains.
-- The front is PINNED: three pairs running, the first divergent row is position 28 of tick 3,
-- vehicle 77ecd026's gate_intake_no_charge stall pick (e0f2bf3a / 06acce00 / 321e4142 across
-- pairs) — and each time the winning stall was pre-claimed by a co-tick 5-minute temp_hold
-- for a DIFFERENT vehicle whose own placement permuted. Everything upstream in the decision
-- stream is identical, so the permuting writer is a NON-decision hold placement in the same
-- tick. NEXT SESSION'S TARGET, in order: (1) find which path books the co-tick
-- [clock, clock+5min) temp_holds (it is NOT place_unplaced_vehicles ORDER BY id, NOT the
-- charge-session loop ORDER BY vehicle_id, NOT prearrival_contracts — all verified stable);
-- candidates: twin.ottoq_sim_stop_charge_session's post-charge hold (its CALLER's iteration
-- feeds it), ottoq_replan_stranded_undercharge, ottoq_enact_opportunistic_charge, and
-- ottoq_book_stall/find_and_book internals; (2) the score-only ORDER BY tail from the sweep
-- (ottoq_svc_to_stall_type etc.). The instrument stands: run the pair, align tick-3 decisions
-- by decision_seq, diff at position 28.
--
-- ── PAIRS 8–10, after 0104/0105/0106 (2026-08-29) — CONVERGENCE ───────────────────────────
-- The pair-7 hypothesis was INVERTED by the ledger trace. Phase order (world -> proposals ->
-- decide_tick -> place_unplaced) proves the 5- and 15-minute temp_holds are written AFTER
-- decide_tick by place_unplaced_vehicles: they were victims of the cascade, not its cause.
-- The true first divergent write of tick 3 was a WORLD-PHASE 30-minute hold from
-- twin.ottoq_opportunistic_scan -> ottoq_enact_opportunistic_charge, and behind it TWO
-- defects in one function: the simulated tech verdict drew its coin from
-- approval_id::text — a gen_random_uuid, different every run (ledger: 5f8af8a5 declined in
-- one arm, approved in the other; 814c9bc7 the reverse) — and the verdict cursor had no
-- ORDER BY at all. Fixed by 0104 (run-stable salt vehicle:type:requested_at + total order).
--
-- PAIR 8 (966dd746/7814f235): COMMAND stream byte-identical over all 12 ticks (671/671,
-- h_cmd cd1269c4), decisions identical ticks 1–11. The tick-12 residue was not a cursor: the
-- ottoq-orchestrator-agent edge function (Nemotron LLM, fired from decide_and_dispatch every
-- 3rd tick) returned HTTP 503 in one arm, 429 then a DIFFERENT policy batch in the other.
-- A sampling LLM cannot be replayed by seed. Fixed by 0105: cert_harness runs quiesce the
-- LLM proposer (the 0056 cuOpt precedent, applied to the orchestrator).
--
-- PAIR 9 (466a8404/2b970077): commands, decisions AND bookings byte-identical
-- (h_cmd cd1269c4, h_dec 2af3a71b at 1856/1856, h_bkg 0752973e). Event multiset differed by
-- exactly six vehicle.state_changed rows stamped 23:08:00.602 — the ottoq-depot-tick cron
-- (ottoq_cron_tick) treats ANY running run as "depot live" and ran the production brain
-- (world_advance, orchestrate-tick submit=true, wave-admit commit=true) against the arm that
-- was alive on the */2-minute boundary; wave-admit flipped six gate vehicles. Fixed by 0106:
-- the cron's idle gate ignores cert_harness runs. Also catalogued: the event projection's
-- entity_id is a per-run RANDOM uuid for entity_type ocpp_session / service_detail_record /
-- sim_run (the bookings projection already excludes such ids); the projection below now
-- masks those three to '-'. ottoq_decisions.enacted_action for bay_reconcile rows embeds a
-- per-run leg_id — full-payload decision comparisons must exclude it (the projection already
-- does).
--
-- PAIR 10 (47643e53/7596fab7), all three fixes live: ALL FOUR STREAMS BYTE-IDENTICAL —
--   h_cmd cd1269c42ea0571b587890921da8e78b   (671 commands)
--   h_dec 2af3a71bafbba80f3ff285730e2224d3   (1856 decisions)
--   h_evt 6b191843f04c167b01d50720e8a7bce9   (2675 events, stable projection)
--   h_bkg 0752973ea5337e86fa07893e4226a584
-- and h_cmd/h_dec/h_bkg are identical ACROSS pairs 9 and 10 (four arms, one stream).
-- Scope of the claim, stated honestly: scenario busy_day, seed 424242, 12 ticks, world
-- fingerprint 3c903a8f, external proposers quiesced (cuOpt per 0056, LLM orchestrator per
-- 0105), production cron standing off (0106), volatile per-run ids excluded from the event
-- projection. Next rungs for a standing certification: more seeds, longer horizons, and the
-- C7 property test wrapping this instrument.
--
-- ── PAIRS 11–15, the SECOND SEED (2026-08-30) — the 424242 green was seed-lucky ──────────
-- PAIR 11 (seed 171717, first non-424242 seed ever paired): DIVERGED FROM TICK 1 (742 vs
-- 768 commands) with MATCHING world fingerprints. Root: vehicle_need_profile is persistent
-- state every run mutates (last_wash_at et al.) and nothing on the harness path redraws it —
-- each arm inherited the previous run's clocks, and generate_service_manifest's wash
-- backstop read them (one arm drew an exterior_wash atom, the other didn't). The 424242
-- pairs had passed only because CONSECUTIVE IDENTICAL RUNS form a fixpoint. Fixed by 0107:
-- twin.ottoq_sim_start_run now calls ottoq_run_boot_draw (full seed-deterministic profile
-- redraw, all clocks sim-anchored) before stamping the fingerprint, and the fingerprint
-- gains the profile section.
-- PAIR 12 (post-0107): commands/events/bookings equal; one triage_confirm decision moved
-- tick 11<->12, and the fingerprints differed on provably equal starts. A double-boot-draw
-- probe showed the profile redraw perfectly idempotent (differing_columns=[NONE]) — the
-- decision drift was ANOTHER 0054-family cursor: advance_visit_atoms' concurrent-atoms
-- admission (ORDER BY urgency, charging, last_state_change LIMIT 30 — no run-stable tail);
-- the fp noise was config.condition_drawn_run (the run's own uuid, stamped by the boot
-- draw). Both fixed by 0108, which also run-scoped the tech_greenlight dedup guard (its
-- NOT EXISTS read approvals across runs — a live cross-run leak on the same sim-day replay).
-- PAIR 13 (post-0108, seed 171717): TOTAL EQUALITY — fp f3e03b9a and all four streams:
--   h_cmd e08fad64 (773) · h_dec 660ca0da (2015) · h_evt 20dd7395 (2955) · h_bkg 74e42e0e
-- PAIR 14 (seed 424242): fp differed across arms AND streams forked — two separate causes,
-- both instructive. (a) fp: profile.wear_km_applied carries the PREVIOUS run's mid-run
-- watermark (boot's 1c anchor no-ops on a fresh run), so arms whose predecessors ran
-- different seeds fingerprint differently; behaviorally dead (mark_serviced treats a
-- foreign-run watermark as unknown) — normalized at boot by 0109. (b) streams: arm B hit
-- the 45s budget and finished its last 2 ticks in a SECOND transaction — now() jumps
-- between transactions and the REAL-domain proposal TTLs (expires_at >= now()) behave
-- differently than in a one-transaction arm. HARNESS RULE, now standing: an arm must run
-- its whole tick loop in ONE transaction (budget raised to 90s below). The wall-domain
-- proposal TTL remains an OPEN FRONT for the live path, where every tick is its own
-- transaction minutes apart — a sim-domain TTL is the eventual fix.
-- PAIR 15 (one-transaction arms, seed 424242): TOTAL EQUALITY —
--   fp 2797c30d · h_cmd 815e18a3 (898) · h_dec 054809ea (2199) · h_evt c0295473 (3064) ·
--   h_bkg 77f9bf18
-- POST-0109 PROBE (rolled back): two boots at 171717, one after a 424242 run and one after
-- a 171717 run, produced IDENTICAL fingerprints (e2902297) — the start world is a pure
-- function of the seed, independent of run history. Note: 0107/0109 change the canonical
-- fingerprints and stream hashes; the values above are the post-0109 canonicals.
--
-- ── PAIR 16 + THE ONE-COMMAND CHECK (2026-08-30) ──────────────────────────────────────────
-- PAIR 16 (seed 424242, 24 ticks = sim 02:00->14:00, one transaction per arm): TOTAL
-- EQUALITY — fp 1fed4510 · h_cmd bdc5de12 (1344) · h_dec aec53de0 (3626) · h_evt 8c667786
-- (5928) · h_bkg af8a7bb9. The 12-hour horizon holds.
-- 0110 folds this whole instrument into one callable:
--     SELECT public.ottoq_determinism_pair(<seed>[, ticks[, scenario]]);
-- Two arms, five values captured per arm with these exact projections, verdict returned AND
-- stamped on both run rows (validation_status passed|failed, hashes in validation_notes) so
-- a dropped client can still read it. Its FIRST exercise proved the red path: a
-- deliberately budget-cut pair computed unequal arms and drove the failed branch (caught a
-- vocabulary bug in the draft while doing it — validation_status allows only
-- pending/passed/failed/inconclusive; fixed in 0110b). A later budget-cut pair where both
-- arms happened to cut at tick 2 was byte-equal even truncated.
--
-- ── PAIRS 17-19 — THE FIRST PAIR AFTER PRODUCTION (2026-08-30, post-0111..0114) ───────────
-- PAIR 17 (seed 171717, first pair after the production E2E e8a0ba01 ran on this depot):
-- FAILED with a brand-new signature — both arms booted fp-EQUAL (e2902297) yet diverged
-- from tick 1, in stall assignment. Root, traced to the row: vehicles.target_soc and
-- current_soc_updated_at are in-run state that survives teardown OUTSIDE both the boot
-- draw and the fingerprint. Arm A charged vehicle 091fa637 to target 90; arm B booted
-- "fp-identical", and ottoq_l2_optimize_assignments' eligibility (current_soc <
-- COALESCE(target_soc, default) - 0.5) read arm A's leftover target — one extra vehicle in
-- one queue at tick 1, cascade from there. Pairs 8-16 never saw it because back-to-back
-- IDENTICAL cert runs leave IDENTICAL leftovers (the 424242 fixpoint lesson, again):
-- production on the cert depot broke the fixpoint and exposed the class. Also surfaced:
-- 33 live approvals from completed pre-0097-era runs (among them an indepot_reassign
-- approved AFTER its own expiry by an auto-gate) — constant inputs, not the fork, but
-- 0097 violations. ALL FIXED BY 0115: boot draw resets target_soc/current_soc_source/
-- current_soc_updated_at; fingerprint extended with target_soc + current_soc_updated_at
-- (per its own rule this line is the justifying probe); stale approvals expired with
-- provenance. NOTE: production sessions never call the boot draw (0111) — a real feed's
-- SoC state is never reset by this.
-- PAIR 18 (post-0115): decisions BYTE-EQUAL (h_dec cf6fb562 both arms — the target_soc
-- channel is dead) and commands equal ticks 1-11; ONE residual command at the final tick
-- (arm B sent one arrived-at-gate vehicle to long staging at the horizon; arm A did not).
-- The driver is the same CLASS — cross-run state outside fingerprint + boot reset — not
-- yet pinned to a column. Known member identified by inspection while hunting:
-- vehicles.owning_sim_run_id (admit_stranded's claim column: set to the claiming run,
-- COALESCE-kept forever, filters candidates across runs, in neither fp nor any reset).
-- Cross-pair stream identity also varies with the pair transaction's wall now() — the
-- wall-domain TTL front from pair 14, still the standing open front for the live path.
-- PAIR 19 (immediately after 18): TOTAL EQUALITY — fp ea2b7c32 · h_cmd 118d3fda ·
-- h_dec cf6fb562 · h_evt 92e81190 · h_bkg aa324fad. (Superseded as canon by 0116 below.)
-- PAIR 20 (seed 424242, first cross-SEED lineage post-0115: arm A's predecessor ran
-- 171717): the pair-14(a) signature under the new fingerprint — ALL FOUR STREAMS
-- BYTE-EQUAL, fingerprints UNEQUAL (465f7301 vs 8476972c). Root: stalls.reserved_at.
-- ottoq_reserve_stall stamps it, the fp has always covered it, and NO teardown cleared it —
-- release_depot cleared reserved_by + reservation_expires_at and left the dead
-- reservation's timestamp behind. Measured: 158 flagship stalls carrying an orphaned
-- reserved_at across 12 distinct values — the predecessors' reservation pattern, varying
-- with predecessor seed; behaviorally dead (readers gate on reserved_by/expires — and the
-- equal streams prove it). FIXED BY 0116: both release clear-sites also null reserved_at
-- (world-reset AND ledger-only), standing orphans repaired.
-- PAIR 21 (424242, post-0116): PASSED — fp 8476972c both arms, streams identical to pair
-- 20's (fp-only fork closed). PAIR 22 (171717, post-0116, arm A booting from the 424242
-- lineage): streams ALL EQUAL again, fp forked again (arm A 3419d654, arm B ea2b7c32 — arm
-- B landing exactly on the old same-lineage value). The residue family behind it is now
-- ENUMERATED, not guessed: vehicles.config keys written in-run that the boot draw neither
-- draws nor strips, so their presence pattern tracks which RUNS ran — measured on the
-- flagship post-pair-22: deploy_gate (17 vehicles), flagged_issue/_type (4), exception (3),
-- bay_eviction (3), nightly_soc_target (4), last_balance_charge_at (1), deploy_gate_override
-- (1), plus accumulating last_calibration_at + lifetime_miles (all 100 seeded). One-by-one
-- normalization is a losing game — the systematic close is the V7 sweep (see OPEN FRONT).
--
-- ── THE STANDING CANON (post-0116, ledger-backed) ─────────────────────────────────────────
-- STREAMS are seed-pure and CROSS-PAIR STABLE — byte-identical across every post-0115 arm
-- of the same seed regardless of lineage (six consecutive arms over pairs 18-22):
--   171717/12t: h_cmd 118d3fda · h_dec cf6fb562 · h_evt 92e81190 · h_bkg aa324fad
--   424242/12t: h_cmd 185a0a6b · h_dec c2e0b16c · h_evt 97a1e359 · h_bkg d536d9c3
-- FINGERPRINTS have same-seed-lineage fixpoints (171717 -> ea2b7c32, 424242 -> 8476972c)
-- but the FIRST boot after a foreign-seed lineage varies with the config-key residue above:
-- until V7 lands, a determinism_pair fired after a different seed (or any non-cert session)
-- may FAIL ON FP ALONE with byte-equal streams — read the notes, don't just read the
-- verdict. Behavioral (stream) inequality is ALWAYS a real defect. 424242/24t re-baseline
-- still pending. Era history: f3e03b9a/2797c30d/1fed4510 post-0109; ea2b7c32 post-0115
-- same-lineage; the values above are post-0116.
-- (Pair 18's "single final-tick staging command" transient is RESOLVED below — it was the
-- 0119 eviction-cursor coin all along, not a lineage transient.)
--
-- ── PAIRS 23-26 — THE V7 CHUNK (0117-0119), AND THE COIN RUN TO GROUND ────────────────────
-- PAIR 23 (171717, post-0117 claim release): fps EQUAL, decisions EQUAL, and the streams
-- split into the two familiar attractors — arm A the Y-stream (pairs 17B/18B: bkg 6a931f19
-- cmd 57ec67dd evt d02a9e20), arm B the Z-stream (pairs 18A/19/22: the standing canon).
-- PAIR 24 (post-0118 state-clock stamp): identical verdict to 23 — 0118's tier fix was
-- real but was NOT the discriminator. The row-level diff pinned it: the ONLY differing
-- command was one final-tick staging placement (vehicle bfbaf0b2), and the only differing
-- bookings were WHICH of vehicle 87098f16's TWO live perimeter_holds (same upper bound,
-- lowers 37m06s apart, rows identical in both arms) got interrupted by the deferred
-- eviction resume. twin.ottoq_sim_vehicle_exception_handler picked with
-- ORDER BY upper(b.during) DESC LIMIT 1 — a heap-order coin on the tie, at TWO sites.
-- Also measured in pair 24: +116 vehicle.state_changed CONVERGENCE PHANTOMS in the
-- dirty-lineage arm (the diff-trigger logs only rows that change; idempotent seeded
-- boot/prime writes no-op in a converged world) — h_evt measures convergence effort, not
-- only behavior; see db/checks/0049.
-- PAIR 25 (post-0119 stable tail): PASSED — fp ea2b7c32 both arms, streams settling on the
-- standing Z-canon exactly (bkg aa324fad · cmd 118d3fda · dec cf6fb562 · evt 92e81190).
-- The coin is dead; Y is unreachable with the tie closed.
-- PAIR 26 (424242, post-0119, fired straight after the 171717 lineage): streams ALL EQUAL
-- and CANON-EXACT (bkg d536d9c3 · cmd 185a0a6b · dec c2e0b16c · evt 97a1e359) — 0119 holds
-- on the second seed from a foreign lineage. Verdict 'failed' on the FIRST ARM'S FP ONLY
-- (cross-lineage 465f7301 vs the 8476972c fixpoint): the documented config-key residue
-- caveat, not a behavior fork. Both seeds now produce their canon streams from ANY lineage.
-- Harness note: the platform now cancels statements at 120s on this connection path —
-- pairs run DETACHED via cron.schedule with SET statement_timeout TO '25min', polled from
-- validation_status, then unscheduled (three invocations were silently killed mid-flight
-- before cron.job_run_details exposed the cancel).
-- OPEN FRONT (named, next campaign chunk): sweep vehicles (and sibling world tables) for
-- ALL columns mutable in-run but absent from fingerprint + boot reset + reset_fleet —
-- owning_sim_run_id first; the first pair after ANY non-cert session on the depot is the
-- reproduction instrument.
--
-- ── THE INSTRUMENT (re-runnable verbatim) ──────────────────────────────────────────────────
-- One arm (repeat per arm; cert_harness is exempt from the metronome and the governor):
--
--   DO $arm$
--   DECLARE v_run uuid; v_t0 timestamptz := clock_timestamp(); v_clock timestamptz; v_status text;
--   BEGIN
--     PERFORM public.ottoq_tick_invariance_reset_fleet('11111111-1111-1111-1111-111111111111'::uuid, 424242);
--     v_run := twin.ottoq_sim_start_run('busy_day', '2026-09-01 02:00:00+00'::timestamptz, 60, 424242, 'cert_harness');
--     BEGIN PERFORM twin.ottoq_sim_prime_deployment(v_run, '2026-09-01 02:00:00+00'::timestamptz, 0.70);
--     EXCEPTION WHEN OTHERS THEN RAISE WARNING 'prime failed: %', SQLERRM; END;
--     LOOP
--       SELECT sim_clock_current, status INTO v_clock, v_status FROM public.ottoq_sim_runs WHERE sim_run_id=v_run;
--       EXIT WHEN v_status <> 'running' OR v_clock >= '2026-09-01 08:00:00+00'::timestamptz;
--       EXIT WHEN EXTRACT(EPOCH FROM (clock_timestamp()-v_t0)) >= 90;  -- pair-14 rule: ONE transaction per arm; a resumed arm shifts now() and the real-domain TTLs with it
--       PERFORM public.ottoq_sim_advance_tick(v_run);
--     END LOOP;
--   END $arm$;
--   -- then run the projection below, then: SELECT ottoq_sim_stop_and_reset(<run>, 'determinism_arm_complete');
--
-- Stream projection for one run (replace :run). Volatile identifiers (booking/leg/event UUIDs,
-- wall-clock created_at) are deliberately excluded; vehicle/stall ids are stable fleet rows.
-- ============================================================================================

WITH r AS (SELECT :run::uuid AS id)
SELECT
  (SELECT md5(COALESCE(string_agg(
      issued_at::text||'|'||vehicle_id::text||'|'||command_type||'|'||COALESCE(payload->>'stall_id','-')||'|'||status||'|'||COALESCE(reason_code,'-'),
      E'\n' ORDER BY issued_at, vehicle_id, command_type, COALESCE(payload->>'stall_id','-'), status), ''))
     FROM public.ottoq_vehicle_commands c, r WHERE c.sim_run_id=r.id) AS h_cmd,
  (SELECT md5(COALESCE(string_agg(
      sim_clock::text||'|'||tick_seq::text||'|'||action_context||'|'||entity_id::text||'|'||outcome_status
      ||'|'||COALESCE(enacted_action->>'verb', proposed_action->>'verb','-')||'|'||COALESCE(proposed_action->>'stall_id','-'),
      E'\n' ORDER BY sim_clock, tick_seq, action_context, entity_id, outcome_status,
                    COALESCE(enacted_action->>'verb', proposed_action->>'verb','-'), COALESCE(proposed_action->>'stall_id','-')), ''))
     FROM public.ottoq_decisions d, r WHERE d.sim_run_id=r.id) AS h_dec,
  (SELECT md5(COALESCE(string_agg(
      event_type||'|'||CASE WHEN e.entity_type IN ('ocpp_session','service_detail_record','sim_run')
                            THEN '-'   -- per-run random ids (pairs 9-10 finding); vehicle/stall/depot ids are stable
                            ELSE COALESCE(entity_id::text,'-') END,
      E'\n' ORDER BY event_type,
                    CASE WHEN e.entity_type IN ('ocpp_session','service_detail_record','sim_run')
                         THEN '-' ELSE COALESCE(entity_id::text,'-') END), ''))
     FROM public.ottoq_events e, r WHERE e.sim_run_id=r.id) AS h_evt,
  (SELECT md5(COALESCE(string_agg(
      lower(during)::text||'|'||upper(during)::text||'|'||vehicle_id::text||'|'||stall_id::text||'|'||purpose||'|'||state,
      E'\n' ORDER BY lower(during), vehicle_id, stall_id, purpose, state), ''))
     FROM public.ottoq_stall_bookings k, r WHERE k.sim_run_id=r.id) AS h_bkg,
  public.ottoq_tick_invariance_metrics((SELECT id FROM r)) AS metrics;
