-- ============================================================================================
-- 0046 — SAME-SEED DETERMINISM ARMS: run the identical world twice; the ledgers must match.
--
-- Chase's repeatability complaint ("very little if any repeatability"), made executable.
-- The claim under test decomposes into two properties:
--   (a) same seed => same INITIAL world (fleet state, wear, cadence, emission gates)
--   (b) same initial world => same EVOLUTION (the 0054/0060 ordering work's territory)
-- A pair that diverges says at least one is false; a triplet says which way it drifts.
--
-- ── VERDICT, first triplet (2026-08-29) — FAIL, with structure ─────────────────────────────
-- Three arms, byte-identical treatment each time:
--   reset:  ottoq_tick_invariance_reset_fleet(depot 11111111, seed 424242)
--   start:  twin.ottoq_sim_start_run('busy_day', '2026-09-01 02:00:00+00', 60, 424242,
--           'cert_harness');  prime_deployment(clock, 0.70);  12 synchronous ticks to 08:00.
--
--   arm | run_id                               | cmds | decisions | events | bookings
--   A   | e8852600-1e8d-4f2c-af92-88dcb46d4ad4 |  507 |      1426 |   3236 |      810
--   B   | c1ca08bb-e91b-4986-a97a-9c4e72e875dc |  526 |      1506 |   3007 |      788
--   C   | de027539-8f2b-4478-978a-cb8eef3a4c5c |  587 |      1698 |    785 |      798
--   All four stream hashes differ on every pair. No arm matches any other.
--
-- TWO DISTINCT BLEEDS, both cross-run state the seeded reset does not cover:
--   1. SCHEDULING DRIFT, monotonic across arms: wash_atoms 84→73→64, soil_index_mean
--      .0381→.0408→.0416, kwh_per_100km 24.06→20.26→13.95, refusal_escalated 134→139→209.
--      Monotonic = cumulative per-vehicle state (wear/soil/cadence/need history) carried
--      between runs. reset_fleet restores SoC/state/stalls/cycles_since_wash only; the
--      harness start path (twin.ottoq_sim_start_run) does NOT re-draw need profiles or
--      re-phase wear the way ottoq_sim_run_scenario's boot does.
--   2. EMISSION SUPPRESSION, cliff-shaped in arm C: vehicle.state_changed 1566→1422→30,
--      stall.state_changed 844→798→0 — while activity continued (58 charge sessions started,
--      116 dispatches completed).
--      ROOT-CAUSED (same day, superseding the flood-guard suspicion this file first recorded):
--      not suppression — MIS-TAGGING. ottoq_active_sim_run_id() cached 'none' in its
--      transaction-scoped GUC when the arm's fleet reset fired triggers before the run row
--      existed, and arm C ran reset+start+ticks in ONE transaction — so 12 ticks of witness
--      events were written sim_run_id NULL / data_source 'production' (arms A/B ticked in a
--      separate transaction and resolved correctly; that procedural difference was the cliff).
--      The same mechanism mis-tagged EVERY run teardown ever: stop flips status before the
--      depot reset, so teardown events found no 'running' run — 4,074 orphaned witness rows
--      measured in one 16-minute window. Fixed by 0092 (no cached misses; GUC pinned at run
--      start and at teardown); check 0045 R12 watches the teardown window permanently.
--
-- ── SECOND PAIR, after 0092–0096 (2026-08-29, arms 05553150 / e1fe726c) ────────────────────
-- Property (a) is now PROVEN: both arms stamped the SAME world fingerprint
-- (3c903a8f2e7dc924ca2a6661f62feb21) — the 0095 whitelist reset + 0093 residue strip close
-- the world completely (rolled-back 8-tick probe: fp_equal=t, zero column diffs).
--
-- Property (b) FAILS, and the first divergence names its mechanisms. Tick 1 is BYTE-IDENTICAL
-- (55 commands, same hash). Divergence begins at tick 2: five 'stage' (ready:true) commands
-- present in arm A, absent in arm B — the task_start staging decision drew differently from
-- an identical world. Two wall-clock/cross-run inputs reach that decision:
--   1. PROPOSAL TTLs LIVE IN THE WALL DOMAIN: greedy proposals get expires_at = now()+120
--      REAL seconds and ottoq_l2_external_proposal filters >= now() — ticks run at variable
--      wall speed, so a proposal straddles the next tick in one arm and is expired in the
--      other (20 proposals in arm A vs 32 in arm B). Same disease class as the 0067
--      reservation-expiry fix; the cure is the same: sim-domain freshness for sim runs.
--   2. ottoq_ops_approvals IS READ WITHOUT RUN SCOPE: the table HAS sim_run_id, but decide's
--      checks filter only vehicle/type/status/created_at — so arm B inherits arm A's
--      approvals (66 approvals written during the pair; 271 accumulated). One run's
--      greenlights leak into the next run's gates.
-- Fix both, then re-run this pair expecting equality tick by tick; the first-divergence
-- bisection above is the debugging loop to repeat if a third mechanism hides behind them.
--
-- ── PAIRS 4 AND 5, after 0097/0098 (2026-08-29) — the horizon moves, the diagnosis lands ──
-- Pair 4 (02ad9218/40cd6a63, after 0097 expired approvals at teardown): ticks 1 AND 2 now
-- byte-identical — mechanism 2 (approvals) confirmed dead. Divergence moved to tick 3:
-- one vehicle (bc55d859) admitted to the overnight drain in one arm only. Root: the
-- admission cursor ORDER BY (deferred count DESC, last_state_change) LIMIT n — same-tick
-- transitions share last_state_change (the sim clock), so the last slot went in heap order.
-- Fixed by 0098 (append id).
-- Pair 5 (908c16bc/de282fc7, after 0098): stall_assignment queue identical through
-- position 28 (the drain fix held); the first divergence is now a forward temp-hold at
-- tick 2 — the same window's hold on stall a06d087f went to fixture vehicle a1111111 in
-- arm A and b2222222 in arm B, and the pairing permutation cascades from there.
--
-- ── THE GENERAL DIAGNOSIS (ending one-at-a-time whack-a-mole) ─────────────────────────────
-- A live sweep of pg_proc for `ORDER BY ... LIMIT` cursors lacking a closing unique key
-- found DOZENS of sites across the tick path, dominated by two families:
--   * `ORDER BY vn.created_at DESC LIMIT 1` — "the latest need" picked by a WALL-clock
--     column whose values tie for rows created in the same transaction (arrival_disposition,
--     book_appointment, decide_wash_triage, plan_opportunistic_charges, readmit_*,
--     record_enacted_booking, reoptimize_reservation_book, reserve_inbound_bays, ...);
--   * score-only ORDER BY with no id tiebreak (the 0054/0067 disease, re-grown since the
--     decide-path rewrite).
-- The remaining work is a 0054-scale sweep: enumerate every site from the live catalog,
-- close each order with the row's unique key, one self-verifying migration, then re-run
-- this pair expecting tick-by-tick equality. The sweep query lives in the session notes;
-- rebuild it as: regexp over pg_proc.prosrc for 'ORDER BY ... LIMIT' minus snippets already
-- carrying id/stall_code/seq columns.
--
-- ── PAIR 6, after 0099 swept the created_at family (2026-08-29, arms b2148f8b/2dc7d9df) ────
-- 0099 closed the 12 `ORDER BY created_at DESC LIMIT 1` latest-need cursors across 10
-- functions with the run-stable `visit_key` tiebreak (visit_key = vehicle:sim-time — a per-run
-- random uuid would NOT do; 0054's rule). Pair 6: tick 2's forward-hold divergence is GONE
-- (ticks 1–2 identical for the third pair running); tick 3's first divergence moved one hold
-- upstream again — vehicle 03726c33's same-tick 5-minute temp_hold landed on stall 06acce00
-- in arm A and 9b1306c1 in arm B, and vehicle 77ecd026's gate intake cascaded from that.
-- FRONT: the same-tick HOLD-BOOKING LOOPS (which vehicle's hold books first / which candidate
-- survives). Next: enumerate the remaining score-only ORDER BY ... LIMIT sites from the sweep
-- (svc_to_stall_type and the tail past the first 40) plus the loops that call
-- book_hold_stall in the twin phase, close each, re-pair. The convergence trend across pairs
-- 3→6 (divergence at tick 2 pos ~1 → tick 3 pos 21 → pos 29 → pos 28-with-fewer-diffs) says
-- the method is working; what remains is finishing the enumeration, not new theory.
--
-- ── PAIR 7, after 0100 closed the service-flow admissions (arms 2ebf111d/4f203026) ────────
-- Command and decision COUNTS are now equal (655/655, 1854/1854) — pure permutation remains.
-- The front is PINNED: three pairs running, the first divergent row is position 28 of tick 3,
-- vehicle 77ecd026's gate_intake_no_charge stall pick (e0f2bf3a / 06acce00 / 321e4142 across
-- pairs) — and each time the winning stall was pre-claimed by a co-tick 5-minute temp_hold
-- for a DIFFERENT vehicle whose own placement permuted. Everything upstream in the decision
-- stream is identical, so the permuting writer is a NON-decision hold placement in the same
-- tick. NEXT SESSION'S TARGET, in order: (1) find which path books the co-tick
-- [clock, clock+5min) temp_holds (it is NOT place_unplaced_vehicles ORDER BY id, NOT the
-- charge-session loop ORDER BY vehicle_id, NOT prearrival_contracts — all verified stable);
-- candidates: twin.ottoq_sim_stop_charge_session's post-charge hold (its CALLER's iteration
-- feeds it), ottoq_replan_stranded_undercharge, ottoq_enact_opportunistic_charge, and
-- ottoq_book_stall/find_and_book internals; (2) the score-only ORDER BY tail from the sweep
-- (ottoq_svc_to_stall_type etc.). The instrument stands: run the pair, align tick-3 decisions
-- by decision_seq, diff at position 28.
--
-- ── PAIRS 8–10, after 0104/0105/0106 (2026-08-29) — CONVERGENCE ───────────────────────────
-- The pair-7 hypothesis was INVERTED by the ledger trace. Phase order (world -> proposals ->
-- decide_tick -> place_unplaced) proves the 5- and 15-minute temp_holds are written AFTER
-- decide_tick by place_unplaced_vehicles: they were victims of the cascade, not its cause.
-- The true first divergent write of tick 3 was a WORLD-PHASE 30-minute hold from
-- twin.ottoq_opportunistic_scan -> ottoq_enact_opportunistic_charge, and behind it TWO
-- defects in one function: the simulated tech verdict drew its coin from
-- approval_id::text — a gen_random_uuid, different every run (ledger: 5f8af8a5 declined in
-- one arm, approved in the other; 814c9bc7 the reverse) — and the verdict cursor had no
-- ORDER BY at all. Fixed by 0104 (run-stable salt vehicle:type:requested_at + total order).
--
-- PAIR 8 (966dd746/7814f235): COMMAND stream byte-identical over all 12 ticks (671/671,
-- h_cmd cd1269c4), decisions identical ticks 1–11. The tick-12 residue was not a cursor: the
-- ottoq-orchestrator-agent edge function (Nemotron LLM, fired from decide_and_dispatch every
-- 3rd tick) returned HTTP 503 in one arm, 429 then a DIFFERENT policy batch in the other.
-- A sampling LLM cannot be replayed by seed. Fixed by 0105: cert_harness runs quiesce the
-- LLM proposer (the 0056 cuOpt precedent, applied to the orchestrator).
--
-- PAIR 9 (466a8404/2b970077): commands, decisions AND bookings byte-identical
-- (h_cmd cd1269c4, h_dec 2af3a71b at 1856/1856, h_bkg 0752973e). Event multiset differed by
-- exactly six vehicle.state_changed rows stamped 23:08:00.602 — the ottoq-depot-tick cron
-- (ottoq_cron_tick) treats ANY running run as "depot live" and ran the production brain
-- (world_advance, orchestrate-tick submit=true, wave-admit commit=true) against the arm that
-- was alive on the */2-minute boundary; wave-admit flipped six gate vehicles. Fixed by 0106:
-- the cron's idle gate ignores cert_harness runs. Also catalogued: the event projection's
-- entity_id is a per-run RANDOM uuid for entity_type ocpp_session / service_detail_record /
-- sim_run (the bookings projection already excludes such ids); the projection below now
-- masks those three to '-'. ottoq_decisions.enacted_action for bay_reconcile rows embeds a
-- per-run leg_id — full-payload decision comparisons must exclude it (the projection already
-- does).
--
-- PAIR 10 (47643e53/7596fab7), all three fixes live: ALL FOUR STREAMS BYTE-IDENTICAL —
--   h_cmd cd1269c42ea0571b587890921da8e78b   (671 commands)
--   h_dec 2af3a71bafbba80f3ff285730e2224d3   (1856 decisions)
--   h_evt 6b191843f04c167b01d50720e8a7bce9   (2675 events, stable projection)
--   h_bkg 0752973ea5337e86fa07893e4226a584
-- and h_cmd/h_dec/h_bkg are identical ACROSS pairs 9 and 10 (four arms, one stream).
-- Scope of the claim, stated honestly: scenario busy_day, seed 424242, 12 ticks, world
-- fingerprint 3c903a8f, external proposers quiesced (cuOpt per 0056, LLM orchestrator per
-- 0105), production cron standing off (0106), volatile per-run ids excluded from the event
-- projection. Next rungs for a standing certification: more seeds, longer horizons, and the
-- C7 property test wrapping this instrument.
--
-- ── PAIRS 11–15, the SECOND SEED (2026-08-30) — the 424242 green was seed-lucky ──────────
-- PAIR 11 (seed 171717, first non-424242 seed ever paired): DIVERGED FROM TICK 1 (742 vs
-- 768 commands) with MATCHING world fingerprints. Root: vehicle_need_profile is persistent
-- state every run mutates (last_wash_at et al.) and nothing on the harness path redraws it —
-- each arm inherited the previous run's clocks, and generate_service_manifest's wash
-- backstop read them (one arm drew an exterior_wash atom, the other didn't). The 424242
-- pairs had passed only because CONSECUTIVE IDENTICAL RUNS form a fixpoint. Fixed by 0107:
-- twin.ottoq_sim_start_run now calls ottoq_run_boot_draw (full seed-deterministic profile
-- redraw, all clocks sim-anchored) before stamping the fingerprint, and the fingerprint
-- gains the profile section.
-- PAIR 12 (post-0107): commands/events/bookings equal; one triage_confirm decision moved
-- tick 11<->12, and the fingerprints differed on provably equal starts. A double-boot-draw
-- probe showed the profile redraw perfectly idempotent (differing_columns=[NONE]) — the
-- decision drift was ANOTHER 0054-family cursor: advance_visit_atoms' concurrent-atoms
-- admission (ORDER BY urgency, charging, last_state_change LIMIT 30 — no run-stable tail);
-- the fp noise was config.condition_drawn_run (the run's own uuid, stamped by the boot
-- draw). Both fixed by 0108, which also run-scoped the tech_greenlight dedup guard (its
-- NOT EXISTS read approvals across runs — a live cross-run leak on the same sim-day replay).
-- PAIR 13 (post-0108, seed 171717): TOTAL EQUALITY — fp f3e03b9a and all four streams:
--   h_cmd e08fad64 (773) · h_dec 660ca0da (2015) · h_evt 20dd7395 (2955) · h_bkg 74e42e0e
-- PAIR 14 (seed 424242): fp differed across arms AND streams forked — two separate causes,
-- both instructive. (a) fp: profile.wear_km_applied carries the PREVIOUS run's mid-run
-- watermark (boot's 1c anchor no-ops on a fresh run), so arms whose predecessors ran
-- different seeds fingerprint differently; behaviorally dead (mark_serviced treats a
-- foreign-run watermark as unknown) — normalized at boot by 0109. (b) streams: arm B hit
-- the 45s budget and finished its last 2 ticks in a SECOND transaction — now() jumps
-- between transactions and the REAL-domain proposal TTLs (expires_at >= now()) behave
-- differently than in a one-transaction arm. HARNESS RULE, now standing: an arm must run
-- its whole tick loop in ONE transaction (budget raised to 90s below). The wall-domain
-- proposal TTL remains an OPEN FRONT for the live path, where every tick is its own
-- transaction minutes apart — a sim-domain TTL is the eventual fix.
-- PAIR 15 (one-transaction arms, seed 424242): TOTAL EQUALITY —
--   fp 2797c30d · h_cmd 815e18a3 (898) · h_dec 054809ea (2199) · h_evt c0295473 (3064) ·
--   h_bkg 77f9bf18
-- POST-0109 PROBE (rolled back): two boots at 171717, one after a 424242 run and one after
-- a 171717 run, produced IDENTICAL fingerprints (e2902297) — the start world is a pure
-- function of the seed, independent of run history. Note: 0107/0109 change the canonical
-- fingerprints and stream hashes; the values above are the post-0109 canonicals.
--
-- ── PAIR 16 + THE ONE-COMMAND CHECK (2026-08-30) ──────────────────────────────────────────
-- PAIR 16 (seed 424242, 24 ticks = sim 02:00->14:00, one transaction per arm): TOTAL
-- EQUALITY — fp 1fed4510 · h_cmd bdc5de12 (1344) · h_dec aec53de0 (3626) · h_evt 8c667786
-- (5928) · h_bkg af8a7bb9. The 12-hour horizon holds.
-- 0110 folds this whole instrument into one callable:
--     SELECT public.ottoq_determinism_pair(<seed>[, ticks[, scenario]]);
-- Two arms, five values captured per arm with these exact projections, verdict returned AND
-- stamped on both run rows (validation_status passed|failed, hashes in validation_notes) so
-- a dropped client can still read it. Its FIRST exercise proved the red path: a
-- deliberately budget-cut pair computed unequal arms and drove the failed branch (caught a
-- vocabulary bug in the draft while doing it — validation_status allows only
-- pending/passed/failed/inconclusive; fixed in 0110b). A later budget-cut pair where both
-- arms happened to cut at tick 2 was byte-equal even truncated.
--
-- ── PAIRS 17-19 — THE FIRST PAIR AFTER PRODUCTION (2026-08-30, post-0111..0114) ───────────
-- PAIR 17 (seed 171717, first pair after the production E2E e8a0ba01 ran on this depot):
-- FAILED with a brand-new signature — both arms booted fp-EQUAL (e2902297) yet diverged
-- from tick 1, in stall assignment. Root, traced to the row: vehicles.target_soc and
-- current_soc_updated_at are in-run state that survives teardown OUTSIDE both the boot
-- draw and the fingerprint. Arm A charged vehicle 091fa637 to target 90; arm B booted
-- "fp-identical", and ottoq_l2_optimize_assignments' eligibility (current_soc <
-- COALESCE(target_soc, default) - 0.5) read arm A's leftover target — one extra vehicle in
-- one queue at tick 1, cascade from there. Pairs 8-16 never saw it because back-to-back
-- IDENTICAL cert runs leave IDENTICAL leftovers (the 424242 fixpoint lesson, again):
-- production on the cert depot broke the fixpoint and exposed the class. Also surfaced:
-- 33 live approvals from completed pre-0097-era runs (among them an indepot_reassign
-- approved AFTER its own expiry by an auto-gate) — constant inputs, not the fork, but
-- 0097 violations. ALL FIXED BY 0115: boot draw resets target_soc/current_soc_source/
-- current_soc_updated_at; fingerprint extended with target_soc + current_soc_updated_at
-- (per its own rule this line is the justifying probe); stale approvals expired with
-- provenance. NOTE: production sessions never call the boot draw (0111) — a real feed's
-- SoC state is never reset by this.
-- PAIR 18 (post-0115): decisions BYTE-EQUAL (h_dec cf6fb562 both arms — the target_soc
-- channel is dead) and commands equal ticks 1-11; ONE residual command at the final tick
-- (arm B sent one arrived-at-gate vehicle to long staging at the horizon; arm A did not).
-- The driver is the same CLASS — cross-run state outside fingerprint + boot reset — not
-- yet pinned to a column. Known member identified by inspection while hunting:
-- vehicles.owning_sim_run_id (admit_stranded's claim column: set to the claiming run,
-- COALESCE-kept forever, filters candidates across runs, in neither fp nor any reset).
-- Cross-pair stream identity also varies with the pair transaction's wall now() — the
-- wall-domain TTL front from pair 14, still the standing open front for the live path.
-- PAIR 19 (immediately after 18): TOTAL EQUALITY — fp ea2b7c32 · h_cmd 118d3fda ·
-- h_dec cf6fb562 · h_evt 92e81190 · h_bkg aa324fad. (Superseded as canon by 0116 below.)
-- PAIR 20 (seed 424242, first cross-SEED lineage post-0115: arm A's predecessor ran
-- 171717): the pair-14(a) signature under the new fingerprint — ALL FOUR STREAMS
-- BYTE-EQUAL, fingerprints UNEQUAL (465f7301 vs 8476972c). Root: stalls.reserved_at.
-- ottoq_reserve_stall stamps it, the fp has always covered it, and NO teardown cleared it —
-- release_depot cleared reserved_by + reservation_expires_at and left the dead
-- reservation's timestamp behind. Measured: 158 flagship stalls carrying an orphaned
-- reserved_at across 12 distinct values — the predecessors' reservation pattern, varying
-- with predecessor seed; behaviorally dead (readers gate on reserved_by/expires — and the
-- equal streams prove it). FIXED BY 0116: both release clear-sites also null reserved_at
-- (world-reset AND ledger-only), standing orphans repaired.
-- PAIR 21 (424242, post-0116): PASSED — fp 8476972c both arms, streams identical to pair
-- 20's (fp-only fork closed). PAIR 22 (171717, post-0116, arm A booting from the 424242
-- lineage): streams ALL EQUAL again, fp forked again (arm A 3419d654, arm B ea2b7c32 — arm
-- B landing exactly on the old same-lineage value). The residue family behind it is now
-- ENUMERATED, not guessed: vehicles.config keys written in-run that the boot draw neither
-- draws nor strips, so their presence pattern tracks which RUNS ran — measured on the
-- flagship post-pair-22: deploy_gate (17 vehicles), flagged_issue/_type (4), exception (3),
-- bay_eviction (3), nightly_soc_target (4), last_balance_charge_at (1), deploy_gate_override
-- (1), plus accumulating last_calibration_at + lifetime_miles (all 100 seeded). One-by-one
-- normalization is a losing game — the systematic close is the V7 sweep (see OPEN FRONT).
--
-- ── THE STANDING CANON (post-0116, ledger-backed) ─────────────────────────────────────────
-- STREAMS are seed-pure and CROSS-PAIR STABLE — byte-identical across every post-0115 arm
-- of the same seed regardless of lineage (six consecutive arms over pairs 18-22):
--   171717/12t: h_cmd 118d3fda · h_dec cf6fb562 · h_evt 92e81190 · h_bkg aa324fad
--   424242/12t: h_cmd 185a0a6b · h_dec c2e0b16c · h_evt 97a1e359 · h_bkg d536d9c3
-- FINGERPRINTS have same-seed-lineage fixpoints (171717 -> ea2b7c32, 424242 -> 8476972c)
-- but the FIRST boot after a foreign-seed lineage varies with the config-key residue above:
-- until V7 lands, a determinism_pair fired after a different seed (or any non-cert session)
-- may FAIL ON FP ALONE with byte-equal streams — read the notes, don't just read the
-- verdict. Behavioral (stream) inequality is ALWAYS a real defect. 424242/24t re-baseline
-- still pending. Era history: f3e03b9a/2797c30d/1fed4510 post-0109; ea2b7c32 post-0115
-- same-lineage; the values above are post-0116.
-- (Pair 18's "single final-tick staging command" transient is RESOLVED below — it was the
-- 0119 eviction-cursor coin all along, not a lineage transient.)
--
-- ── PAIRS 23-26 — THE V7 CHUNK (0117-0119), AND THE COIN RUN TO GROUND ────────────────────
-- PAIR 23 (171717, post-0117 claim release): fps EQUAL, decisions EQUAL, and the streams
-- split into the two familiar attractors — arm A the Y-stream (pairs 17B/18B: bkg 6a931f19
-- cmd 57ec67dd evt d02a9e20), arm B the Z-stream (pairs 18A/19/22: the standing canon).
-- PAIR 24 (post-0118 state-clock stamp): identical verdict to 23 — 0118's tier fix was
-- real but was NOT the discriminator. The row-level diff pinned it: the ONLY differing
-- command was one final-tick staging placement (vehicle bfbaf0b2), and the only differing
-- bookings were WHICH of vehicle 87098f16's TWO live perimeter_holds (same upper bound,
-- lowers 37m06s apart, rows identical in both arms) got interrupted by the deferred
-- eviction resume. twin.ottoq_sim_vehicle_exception_handler picked with
-- ORDER BY upper(b.during) DESC LIMIT 1 — a heap-order coin on the tie, at TWO sites.
-- Also measured in pair 24: +116 vehicle.state_changed CONVERGENCE PHANTOMS in the
-- dirty-lineage arm (the diff-trigger logs only rows that change; idempotent seeded
-- boot/prime writes no-op in a converged world) — h_evt measures convergence effort, not
-- only behavior; see db/checks/0049.
-- PAIR 25 (post-0119 stable tail): PASSED — fp ea2b7c32 both arms, streams settling on the
-- standing Z-canon exactly (bkg aa324fad · cmd 118d3fda · dec cf6fb562 · evt 92e81190).
-- The coin is dead; Y is unreachable with the tie closed.
-- PAIR 26 (424242, post-0119, fired straight after the 171717 lineage): streams ALL EQUAL
-- and CANON-EXACT (bkg d536d9c3 · cmd 185a0a6b · dec c2e0b16c · evt 97a1e359) — 0119 holds
-- on the second seed from a foreign lineage. Verdict 'failed' on the FIRST ARM'S FP ONLY
-- (cross-lineage 465f7301 vs the 8476972c fixpoint): the documented config-key residue
-- caveat, not a behavior fork. Both seeds now produce their canon streams from ANY lineage.
-- Harness note: the platform now cancels statements at 120s on this connection path —
-- pairs run DETACHED via cron.schedule with SET statement_timeout TO '25min', polled from
-- validation_status, then unscheduled (three invocations were silently killed mid-flight
-- before cron.job_run_details exposed the cancel).
--
-- ── PAIRS 27-28 — 0120 (whitelist drops last_calibration_at): CORRECT BUT INSUFFICIENT ────
-- PAIR 27 (171717, post-0120): PASSED — new same-seed fp fixpoint c525a339 both arms,
-- streams the standing Z-canon exactly. PAIR 28 (424242, first pair after the 171717
-- lineage): streams canon-exact as always now, fps ffe49a6a (arm A) / 38f347c7 (arm B) —
-- the first-arm-after-foreign-lineage variance SURVIVES 0120, and its mechanism is now
-- pinned at the emitter: ottoq_sim_build_arrival_payload computes the webhook odometer as
-- config.lifetime_miles + SUM(dispatch miles), and the ingest path writes it back — so
-- lifetime_miles ACCRUES per arrival cycle in-run (correcting 0049's earlier "no in-run
-- writer" read; the writer hides behind the payload round-trip, not a column-name
-- mention). Closed by 0121: the cert reset DEALS lifetime_miles from the seed.
--
-- ── PAIRS 29-33 — 0121, THE FIXPOINT MODEL COMPLETED, AND TWO HARNESS LESSONS ────────────
-- HARNESS LESSON 1 (the zombie): job v7_pair28 was never unscheduled and fired 424242
-- pairs every minute through pairs 29-30 — yet every contaminated verdict was later
-- REPRODUCED byte-for-byte under quiet one-shot conditions: concurrent pair invocations
-- serialize or roll back entirely; interference cannot alter committed arms. Pairs now run
-- as TRUE ONE-SHOTS: cron.schedule at a specific 'MI HH24' minute (fires exactly once),
-- unscheduled after the verdict is read. Never '* * * * *' for a multi-minute job.
-- HARNESS LESSON 2 (the transition pair): pairs 29/30 (171717, post-0121) forked on fp
-- with IDENTICAL per-arm values under interference and under quiet — deterministic, not
-- noise: arm A 23092841, arm B 092b70a5. Root: the cert reset does not touch
-- vehicles.current_soc; non-deployed vehicles carry run-final SoCs forward, so the world
-- sits at a per-(seed, behavior-era) SOC FIXPOINT. A behavior-changing migration (0121's
-- dealt odometers shifted PM/charge patterns) MOVES the fixpoint; the first pair after it
-- straddles old->new and fails on fp with byte-equal streams; convergence is ONE STEP.
-- Reset-idempotency was proven directly (two consecutive resets, identical fp sections);
-- seeded_random is hash-pure (hashtextextended, IMMUTABLE).
-- PAIR 31 (171717, clean one-shot): PASSED — both arms at the NEW fixpoint 092b70a5,
-- streams the standing Z-canon. The predicted one-step convergence, verified.
-- PAIR 32 (424242, transition): streams mint the post-0121 424242 canon — bkg ea089ec6 ·
-- cmd dcc9144e · dec de709c77 · evt 76364859 (matching the zombie-era values exactly) —
-- fps 350bf848 -> d9d94a7b (the new 424242 fixpoint candidate).
-- PAIR 33 (424242, confirm): PASSED — both arms at the new fixpoint d9d94a7b, streams the
-- post-0121 424242 canon. One-step convergence verified on the second seed.
--
-- ── PAIRS 34-39 — THE CORE-CERT GATE: 0122 TRANSITION, 24T CANON, AND THE P39 CATCH ───────
-- The founder's gate for everything above the core: the matrix must go green over and over
-- before any AI/agent layer work starts. Sequence run 2026-08-30 (all quiet one-shots).
-- PAIR 34 (171717/12t, post-0122 transition): fp-only fork exactly per the operating rule —
-- arm A 23092841, arm B at the standing fixpoint 092b70a5, streams canon-exact both arms
-- (runs 50bc1e69/64e28292). 0122's TTL-sweep fix is stream-invisible at 12t (cuOpt is
-- structurally absent from cert runs; the sweep no longer insta-expires, but no pending
-- proposals exist to keep). Throwaway by rule.
-- PAIR 35 (171717/12t, confirm): PASSED — both arms fp 092b70a5, streams the standing
-- 12t canon aa324fad · 118d3fda · cf6fb562 · 92e81190 (runs 9907e1a9/ee0383e6). The
-- 171717/12t fixpoint did NOT move under 0122 — convergence pulled the world straight back.
-- PAIR 36 (171717/24t, transition): fp-only fork — arm A booted at the 12t fixpoint
-- 092b70a5 (the world had been living at 12-tick horizons), arm B at the emerging 24t
-- fixpoint; STREAMS EQUAL both arms and they MINT the 171717/24t canon: bkg d9d817bd ·
-- cmd e704dfb4 · dec 8914c57d · evt 9dba2c1f (runs 6c11745d/1abdab3c). A longer horizon
-- moves the fixpoint too — more arrival cycles, different final SoCs. Same rule, new axis.
-- PAIR 37 (171717/24t, confirm): PASSED — both arms fp b5d05799 (the 24t fixpoint),
-- streams the 24t canon exactly (runs fff097aa/f239b5fa). 171717 column fully green.
-- PAIR 38 (424242/24t, transition): fp-only fork as expected (arm A fcd44b57 straddling),
-- arm A streams minting the 424242/24t canon candidate: bkg d2f8c144 · cmd 4c119966 ·
-- dec 10c1f3a4 · evt d54195c1 (runs 7a1f5a66/f0d7da76). Throwaway by rule.
-- PAIR 39 (424242/24t, confirm): **FAILED ON STREAMS — the gate's first real catch.**
-- fps EQUAL at 8de3415f (the fixpoint converged) but every stream forked: arm A
-- 6340041e · a1129be5 · 2d533252 · 045100f1 vs arm B reproducing the P38 candidate
-- exactly (runs 5614402c/57b14885). By rule 1 this is a REAL DEFECT, and the row-level
-- diff ran it to ground: one stage command shifted a tick, tick-22 bay_reconcile chose
-- bind-vs-displace differently, first divergent write 12:45:24 — vehicle 9f5d69bb's wash
-- and detail atoms booked in opposite order, steered by WHICH copy of the vehicle's
-- reopened visit the latest-need cursor read. Inside a pair transaction created_at is
-- frozen and visit_key embeds (vehicle, sim clock), so arm B's second-visit row ties arm
-- A's leftover copy EXACTLY and LIMIT 1 picks by heap — a 0054-class coin that needs a
-- vehicle on its SECOND visit, which is why 12t pairs never saw it and the 24t gate did.
-- Census: 13 latest-need cursors in 11 functions, 4 already scoped, NINE not. Closed by
-- 0123 (all nine run-scoped, 0020 zero-uuid convention; decide_tick's two cursor sites
-- anchored per-site after the first apply correctly aborted on a third anchor match — the
-- arrival-admission EXISTS gate, a different class, deliberately left for its own census).
--
-- ── PAIR 40 — 0123 NECESSARY BUT NOT SUFFICIENT; THE FULL VISIT-LEDGER CLASS (0124) ──────
-- PAIR 40 (424242/24t, post-0123 transition; runs cc765a66/f2b72fae): fps EQUAL at the
-- P39 fixpoint 8de3415f, STREAMS STILL FORKED — the same two variants as P39 with the
-- arms SWAPPED (arm A now the P38 candidate d2f8c144·4c119966·10c1f3a4·d54195c1, arm B
-- the 6340041e variant). Two harness lessons first: (1) cron.job_run_details lies for
-- multi-statement jobs — it logged "succeeded/SET/1s" while the pair's SELECT was still
-- running; pg_stat_activity is the truth for in-flight detached pairs. (2) A cancelled
-- diagnostic (60s MCP client timeout) keeps running server-side — pg_cancel_backend it.
-- The archaeology was one query this time: the ENTIRE h_cmd diff is one stage command
-- (vehicle d0887837, 13:00 in B vs 13:30 in A), rooted at tick 22's bay_reconcile
-- (arm A displace_and_bind, arm B bind_bay_occupant) — which itself follows from the
-- 12:45:24 wash-vs-detail purpose swap for 9f5d69bb (A: detail 21min then wash; B: wash
-- 10min then detail — so at 13:00 the bay is busy in A, free in B). The purpose comes
-- from ottoq_visit_wants_detail() — an EXISTS gate over ottoq_visit_needs with NO run
-- scope — and the crediting writer mark_visit_atoms_done() turned out to be a BARE
-- latest-need cursor (ORDER BY created_at DESC LIMIT 1, no visit_key tiebreak, no run
-- scope — older than 0099, invisible to the 0123 census which keyed on the tiebroken
-- form). Full census of ottoq_visit_needs: 51 functions, ~95 sites, three unscoped
-- shapes — bare cursors, membership gates, one depot-wide status-rewrite UPDATE.
-- Closed by 0124: 32 sites in 20 functions run-scoped (strict zero-uuid where
-- p_sim_run_id exists; an in-place resolve-the-running-run subquery for the paramless
-- helpers — no signature changes). Janitors, the carryover resolver, reporting reads,
-- and the OR-NULL departure gate stay deliberately unscoped (cross-run by design).
-- Prediction (falsifiable): pairs 41+ land both arms on ONE stream set per seed.
--
-- ── PAIRS 41-46 — 0124 VERIFIED ON 424242; THE 171717/24T GHOST FRONT OPENS ──────────────
-- PAIR 41 (424242/24t, post-0124): **PASSED** — both arms fp 8de3415f (unchanged), streams
-- ONE set: bkg 6340041e · cmd a1129be5 · dec 2d533252 · evt 045100f1 (runs dd201b8f/
-- e4fb3952). The run-pure canon is a THIRD behavior — neither cross-contaminated variant
-- was privileged. PAIR 42 (confirm): PASSED — canon reproduced exactly (c619fd87/cd94a989).
-- 424242/24t GREEN, canon minted: 6340041e·a1129be5·2d533252·045100f1 @ fp 8de3415f.
-- PAIR 43 (171717/24t, transition): fp-only fork (760e435c / dc203e36), STREAMS EQUAL at
-- the new 171717/24t candidate cmd f6a5a00c — textbook transition (06b67c4b/b6ef091b).
-- PAIR 44 (171717/24t, confirm): **FAILED ON STREAMS** — fps equal (dc203e36), h_dec
-- EQUAL, bkg/cmd/evt forked (7998389f/its arm B). Archaeology: the entire cmd diff is ONE
-- enter_wash (5cee8fb3, 13:00, WSH-02 vs WSH-03); the true first divergence is SIX SIM
-- HOURS earlier — the 06:00 prearrival sweep (reserve_inbound_bays -> book_workflow_legs,
-- 10-min shift walk) placed vehicle 0ea2ccfe's and aff36072's future detail bookings one
-- 10-min slot apart (12:25:08.704248 vs 12:35:08.704248 — IDENTICAL seeded jitter, base
-- shifted one slot; original plan 09:43-10:04 in the why-text of BOTH arms). One arm's
-- find_and_book refused a probe the other accepted. Ruled OUT by direct read: visit-ledger
-- reads (0124), carryover consumption (none — consumed_by null across the lineage),
-- policy_get (keyed lookups, no cursors), prearrival cursor order (total, 0054-stamped),
-- free_between's booking conflict (strict run filter), charger heartbeats (same-seed arms
-- write identical values). NAMED SUSPECT (unverified): STALL-OCCUPANCY GHOSTS —
-- stalls.current_vehicle_id left set by teardown for vehicles mid-wash at the 14:00
-- horizon cut (171717/24t ends with a wash queue running to 14:26; 424242 does not —
-- the seed-specificity). A ghost on a wash bay engages free_between's occupancy guard
-- ([now_sim, +45..240min] with no legs to project) and blocks the 09:43-10:0x probes in
-- one arm only. FALSIFIABLE TEST: inspect stalls.current_vehicle_id vs vehicles'
-- current_stall_id on the quiet world right after a teardown; ghosts -> 0125 clears the
-- stall side at release, then 171717/24t transition+confirm must go green.
-- PAIR 45 (424242/12t, transition): fp-only fork (7d7bec4e / d9d94a7b), streams EQUAL at
-- the new 12t canon (07fe9557/...). PAIR 46 (confirm): **PASSED** — both arms fp d9d94a7b,
-- streams bkg 9ed052b8 · cmd 413837dc · dec 482309a0 · evt ffd06c20 (2ef89737/...).
-- 424242/12t GREEN at the new canon (old post-0121 canon retired by run-purity).
--
-- ── PAIRS 47-52 — THE REST OF THE MATRIX GOES GREEN (fresh seed + second scenario) ───────
-- Every leg the same textbook shape: one fp-only transition (streams equal, the soc
-- fixpoint migrating under run-pure behavior), then a confirm PASS at the new fixpoint.
-- PAIR 47 (171717/12t, transition): fps 23092841 -> 092b70a5, streams equal (447e95da).
-- PAIR 48 (171717/12t, confirm): PASSED — fp 092b70a5 (unchanged from post-0121!),
--   new canon bkg aa324fad · cmd 1433b93f · dec cf6fb562 · evt 92e81190 (2fe0095d) —
--   only h_cmd moved under 0123/0124; bkg/dec/evt survive from the old canon.
-- PAIR 49 (314159/12t, FRESH SEED, transition): fps fd10cb8c / 24b807f0, streams equal
--   (1a8b88ce). A never-before-run seed needed exactly the predicted two pairs.
-- PAIR 50 (314159/12t, confirm): PASSED — fp 24b807f0, canon minted: bkg 24a4a0b4 ·
--   cmd 5beb3b43 · dec e9ed6ee8 · evt fda87aa6 (0aaacc56).
-- PAIR 51 (normal_day 171717/12t, transition): fps 22ea60f0 / 3ece9fbe, streams equal
--   (0e1a9970). PAIR 52 (confirm): PASSED — fp 3ece9fbe, canon: bkg a88de84f ·
--   cmd a3680029 · dec 5b4826fc · evt fadf837a (050e97e1). Second scenario green.
-- GHOST CHECK (quiet world, post-P52 teardown): ZERO stalls with current_vehicle_id set
-- on the flagship depot — teardown clears the stall side cleanly here. The occupancy-ghost
-- hypothesis for P44 is WEAKENED but not dead (P52's teardown was 12t/normal_day, not the
-- 171717/24t mid-wash horizon cut the theory needs). Sharper evidence from the matrix:
-- 171717/12t PASSED while 171717/24t forked, and both horizons run the SAME 06:00
-- prearrival sweep over an identical-to-tick-12 trajectory — so the P44 carrier is
-- LINEAGE-BORNE boot-world state, not intrinsic to the sweep. PAIR 53 re-runs 171717/24t
-- from tonight's different lineage as the discriminating experiment: pass = the fork
-- needs the specific post-171717/24t leftover state; fail = robust reproducer with
-- fresh post-teardown evidence.
-- PAIR 53 (171717/24t from the post-normal_day lineage): FAILED WIDER — fps 3ece9fbe /
-- dc203e36 (transition-shaped) but ALL FOUR streams forked including h_dec, both arms on
-- new hashes (bkg ca2499ed/0516f4e0 · cmd c9b55fef/819dcf5b · dec 3d635974/c2aa26b8 ·
-- evt 42b8bd68/13ab966c; runs 0416646e/...). The column's arm-asymmetry is robust across
-- lineages; only (171717 × 24t) exhibits it — every 12t column and 424242/24t are green.
-- GHOST HYPOTHESIS FALSIFIED by direct observation under its exact required condition:
-- immediately after P53's arm-B teardown (a true 171717/24t horizon cut), the flagship
-- depot shows ZERO seated stalls, ZERO reservations, ZERO seated vehicles. Teardown is
-- clean on the physical side. Vehicle-state census at that instant: 116 offline,
-- 4 staged_for_departure (fp-covered; noted, not implicated).
-- NEXT INSTRUMENT (before more spelunking): the pair grows a BOOT-STATE fingerprint —
-- after each arm's reset+boot+prime, hash the suspect ledgers per table (row count +
-- content hash over ottoq_stall_bookings, ottoq_itinerary_legs, ottoq_visit_needs,
-- ottoq_vehicle_dispatches, plus the vehicles/stalls world projections) into the verdict
-- notes. The next failing pair then NAMES the table whose boot image differs between
-- arms, replacing six-sim-hour backward archaeology with a direct read.
--
-- ── PAIR 54 — THE INSTRUMENT NAMES THE CARRIER ON ITS FIRST OUTING (0125 → 0127) ─────────
-- PAIR 54 (171717/24t, first instrumented pair): **PASSED** outright — and the boot
-- fingerprint showed exactly ONE difference between the arms' starting worlds:
-- bookings.fgn (foreign live-state stall bookings) — arm A n=203, arm B n=206. Arm A's
-- teardown leaked three live rows into arm B's world. World census: 209 leftover
-- live-state bookings across the campaign lineage, essentially all state='interrupted' —
-- written by the vehicle exception-handler path (0119's), retired by NOTHING:
-- release_depot's booking release listed only ('held','active'). The EXCLUDE constraints
-- are run-scoped (sim_run_id WITH =), so leaks never block physically — but live-booking
-- reads filter state IN ('held','active','interrupted',...), and any not also run-scoped
-- see a set that differs between arms. Whether a leaked row intersects a probe window is
-- lineage luck — the observed intermittency (P43 pass, P44 fail, P53 fail, P54 pass).
-- CLOSED by 0127: teardown retires 'interrupted' with held/active (one word in the state
-- list, both feed modes) + one-time repair of the 209 accumulated leaks
-- (release_reason '0127_interrupted_leak_repair'; production NULL-run rows untouched).
-- Prediction (falsifiable): 171717/24t transition+confirm pass, and every healthy pair's
-- boot fingerprint shows bookings.fgn n=0 from now on. Round-2 matrix = pairs 55-66.
--
-- ── PAIRS 55-56 — 0127 HALF-CONFIRMED; THE INSTRUMENT CONVICTS BY ELIMINATION (0128) ─────
-- PAIR 55 (171717/24t, post-0127): PASSED — and bookings.fgn = 0 in BOTH arms: the 0127
-- prediction confirmed, the leak class is dead (runs 91671696/...).
-- PAIR 56 (confirm): FAILED on streams — same two variants as P53 (cmd c9b55fef /
-- 819dcf5b), fps equal, AND the boot images IDENTICAL across all five fingerprinted
-- tables, both classes. With content ruled out wholesale, the carrier had to be
-- heap-order-fed randomness. Archaeology: the primal write is at sim 03:00 — vehicle
-- 5cee8fb3's far-future detail reservation (window 16:38) adopted on WSH-03 in one arm,
-- WSH-02 in the other; the 14:00 enter_wash follows the adopted stall. The site convicts
-- itself in its own 0063 comment: record_enacted_booking's forward-reservation ADOPTION
-- pick orders by booked_at DESC (frozen in a pair — ties), the window (equal — ties),
-- then straight to booking_id DESC — a RANDOM uuid: total within an arm, random between
-- arms. Its sibling in enact_space_assignment got content keys (s.id, b.purpose) back in
-- 0063; this site never did, and the tied candidates differ exactly in stall_id.
-- CLOSED by 0128: b.stall_id, b.purpose inserted before the uuid last-resort — the
-- 0062/0063 discipline completed. Applied mid-ladder BEFORE pair 57 fired, so pairs
-- 57-66 all run post-0128; pairs 67-68 re-run 171717/24t at the ladder's end.
--
-- ── PAIRS 57-68 — ROUND-2 LADDER POST-0128: EVERY 12T COLUMN GREEN; 24T HAS ONE MORE COIN ─
-- All boot fingerprints show bookings.fgn = 0 (0127 holds). The 12t columns each did the
-- textbook transition→confirm under the 0128 behavior shift and are GREEN with new canons:
--   424242/12t: cmd c5432bc9 @ fp d9d94a7b (P59 817cafec t / P60 81ab398e PASS)
--   171717/12t: cmd db2179d3 @ fp 092b70a5 (P61 07619ae0 t / P62 0b83ec77 PASS)
--   314159/12t: cmd 6041f3bb @ fp 24b807f0 (P63 3e4d38f3 t / P64 082f0016 PASS)
--   normal_day: cmd a3680029 @ fp 3ece9fbe — canon UNCHANGED by 0127/0128
--               (P65 cc2805e9 t / P66 9d1f224d PASS)
-- The 24t columns still fork on confirm: P57 (424242/24t transition, streams equal, new
-- cmd 30ae09ef) then P58 (1a3579c8) FAILED — fps equal 8de3415f, streams forked, first
-- divergent write a leg-matched detail REBOOK planned at sim 10:00 landing [12:59] vs
-- [13:09] (the 10-minute slot-walk signature: one arm's find_and_book probe refused once
-- more than the other's). P67 (9af670b5) and P68 (f5b7d07a) forked likewise on 171717/24t.
-- Established: at least one more in-run under-total ordered pick that ties only under the
-- daytime (ticks 12-24) wash/detail rebooking pressure; world-purity is proven (boot
-- images equal, fgn=0), so the class is closed ONLY by the systematic ordering census:
-- enumerate every ORDER BY ... LIMIT 1 / windowed pick across public/ottoq/twin, prove
-- each total over run-stable keys or fix it (0129, next round's opening move — the
-- preliminary extraction already ran; ~200 clauses to triage).
--
-- ── PAIRS 69-74 — ROUND 3: 0129 GREENS THE OPENING COLUMN; 424242/24t NARROWS TO ONE LEDGER ─
-- P69 (171717/24t, first pair post-0129): failed. P70 (confirm, pair run 4e7d2494): **PASSED
-- OUTRIGHT** — the column that opened this entire campaign (P43/P44/P53, the one with NO
-- canon since pair 44) is green for the first time. Post-0129 canon, 171717/24t:
--     bkg 4be004e4 · cmd 0ea5131a · dec 2eebc79f · evt 1fa861d0 @ fp dc203e36
-- (Note for the transition rule: settling took ONE EXTRA pair here — P69 failed, P70 passed.
-- The rule stands as written, but "the first pair may fork" is now "the first pair or two".)
-- P71 (424242/24t, transition): fps 7d7bec4e → 8de3415f, all four streams moved — the 0129
-- behavior shift, as expected. P72 (confirm, run_a 653e0e8e): FAILED — but in the mildest
-- shape this campaign has ever produced: fp EQUAL, boot images EQUAL, h_cmd/h_dec/h_evt all
-- EQUAL, and **h_bkg alone unequal**. P73 (run_a cba09628) then reproduced P72
-- HASH-FOR-HASH (bkg_a 338994b0 / bkg_b 11c0c14f, cmd_a 30ae09ef in both pairs), and P74
-- (run_a 741f7955) PASSED with both arms on bkg ac697818 @ fp 8de3415f.
-- Read the lineage as a whole and the shape is a two-state oscillation, not noise: arm
-- streams alternate between X (cmd d0fe863c / bkg ac697818) and Y (cmd 30ae09ef / bkg
-- 338994b0) by POSITION IN THE LINEAGE, with P73's arm A and P74's arm A booting from
-- byte-identical boot images and still landing on different states. A single passing pair
-- (P74) therefore does NOT green this column — an intermittent fork is still a fork. What
-- P73 bought instead is worth more: a fork that reproduces exactly is a fork that can be
-- dissected.
--
-- ── THE DISSECTION (P72/P73) — CONVICTED FROM THE MOVER'S OWN LEDGER (→ 0130) ─────────────
-- The h_bkg multiset difference is exactly EIGHT rows: two vehicle PAIRS trading slots, one
-- detail pair and one wash pair, all beyond the 14:00 run horizon (which is why no command,
-- decision or event could differ — the rows never enact):
--     arm A: 9e05d00e → c9466ca6 @15:55 | 9f5d69bb → ec443362 @16:05
--     arm B: 9f5d69bb → c9466ca6 @15:55 | 9e05d00e → ec443362 @16:05
-- Each row's `why` names a window ten hours earlier than its own `during`. That dates them:
-- ottoq_booking_why prints p_from/p_to and the stall's own code, so a row whose why
-- disagrees with its window was WRITTEN early and MOVED later. The mover keeps an audit
-- trail, and the trail closes the case — public.bay_reservation_reconcile_2026_08_02, both
-- arms, sim 13:00, defer_seq 3, all four rows entering with old_from = 12:45:
--     arm A  9e05d00e detail  12:45 → 15:55 (keeps c9466ca6)   9f5d69bb → 16:05
--     arm B  9f5d69bb detail  12:45 → 15:55 (takes c9466ca6)   9e05d00e → 16:05
-- Two bookings, IDENTICAL lower(during), and ottoq_reconcile_bay_reservations drives its
-- deferral loop on `ORDER BY lower(b.during)` and nothing else. The body walks each booking
-- forward and takes the first non-colliding window, so the row the heap hands over first
-- wins the earlier bay. The 06:00 and 10:00 defers in the same lineage tied too, but only
-- between one vehicle's OWN two bookings, whose outcomes coincide; 13:00 was the first
-- CROSS-VEHICLE tie, and it is the entire fork.
-- WHY 0129 MISSED IT — the lesson worth more than the fix: 0129's census extracted
-- `ORDER BY ... LIMIT n`, DISTINCT ON heads and window frames, i.e. every shape that picks
-- ONE row. This site picks none — it is a FOR ... IN SELECT ... ORDER BY ... LOOP with no
-- LIMIT. A cursor loop LOOKS total because it visits every row, and it is total in its set;
-- but when the body mutates a resource the rows compete for, VISIT ORDER decides outcomes
-- exactly as a LIMIT 1 does. New standing rule (§4 below). The re-census over that shape
-- found 49 cursor loops, the great majority already carrying 0050/0054/0059-era run-stable
-- tails — including this site's own sibling ottoq_activate_due_bay_reservations, which
-- orders `(lower(during) <= p_clock) DESC, lower(during), b.booking_id`. Four did not, and
-- 0130 totalizes them: reconcile_bay_reservations (the carrier), book_workflow_legs
-- (`ORDER BY l.seq` — the 0129 leg-seq family, missed site, and the depot's principal
-- forward booker), plan_overnight_wave (due_at, current_soc — no id tail) and
-- sim_energy_controller (issued_at, created_at — created_at is frozen inside a pair, so it
-- can never break a tie). Verification = pairs 75-86, the full six-column re-certification
-- ladder (both 24t columns, then all four 12t columns, transition + confirm each).
-- 1. STREAM inequality is ALWAYS a real defect. No exceptions, any lineage, any era.
-- 2. FP-only inequality is the soc/residue fixpoint moving: expected on the FIRST pair
--    after any behavior-changing migration and after any foreign-seed/non-cert session.
--    Run one throwaway TRANSITION PAIR per seed, then read verdicts; the confirm pair
--    must pass at the new fixpoint or something real is wrong.
-- 3. STANDING CANON — ***NO LONGER MAINTAINED HERE. QUERY IT (0131).***
--        SELECT * FROM public.ottoq_cert_matrix();
--    This block was hand-typed, and by round 3 several of its hashes were simply wrong while
--    still labelled "standing" — caught only because a human happened to re-read them. That is
--    the precise failure the company rule exists to prevent: a number that cannot be
--    regenerated from its evidence is a number nobody should trust, ours included. Every hash
--    already lives in ottoq_sim_runs.validation_notes, so the matrix is a QUERY, not a comment,
--    and it cannot go stale. It returns per column: pairs_seen, consecutive_passes, green,
--    the canon (fp/cmd/dec/evt/bkg), the last pair's two run IDs, and a history string
--    (oldest-first, P=pass f=fork).
--    THE BAR IS ALSO RAISED THERE, and the raise is retroactive. green now requires TWO
--    consecutive most-recent pairs passing on an IDENTICAL canon, not one confirm pair. Pair 74
--    is why: on 424242/24t the lineage ran f,f,PASS and the column was not fixed at all — the
--    pass was a two-state coin landing favourably, and the next dig found the live carrier
--    (0130). Under the old single-confirm rule several columns below were called green on ONE
--    passing pair; under the new rule they are not green until re-confirmed. Those earlier
--    calls were correct under the rule as it was written — the RULE was too weak, not the
--    reading — and the honest consequence is that the 12t columns need a third pair whenever
--    their transition pair forks.
--    (post-0124 hand-typed snapshot; HISTORICAL, for lineage reading only — do not cite):
--      424242/24t: bkg 6340041e · cmd a1129be5 · dec 2d533252 · evt 045100f1 @ fp 8de3415f
--      424242/12t: bkg 9ed052b8 · cmd 413837dc · dec 482309a0 · evt ffd06c20 @ fp d9d94a7b
--      171717/12t: bkg aa324fad · cmd 1433b93f · dec cf6fb562 · evt 92e81190 @ fp 092b70a5
--      314159/12t: bkg 24a4a0b4 · cmd 5beb3b43 · dec e9ed6ee8 · evt fda87aa6 @ fp 24b807f0
--      normal_day 171717/12t: bkg a88de84f · cmd a3680029 · dec 5b4826fc · evt fadf837a @ fp 3ece9fbe
--    171717/24t: NO CANON — the open column (pairs 44/53). Permanent close option if
--    transition pairs ever grate: deal current_soc at cert reset (one more transition).
-- 4. A CURSOR LOOP IS A PICK (0130). Any `FOR ... IN SELECT ... ORDER BY ... LOOP` whose
--    body mutates state the rows compete for is as order-decisive as an `ORDER BY ... LIMIT
--    1`, and its ORDER BY must be total over run-stable keys by the same 0062/0063 rule:
--    content keys first, a per-run uuid only as the last resort for byte-identical rows.
--    Ordering censuses MUST cover the no-LIMIT cursor shape — 0129's did not, and the site
--    it could not see (reconcile_bay_reservations) cost round 3 four extra pairs.
-- OPEN FRONT (named, next campaign chunk): sweep vehicles (and sibling world tables) for
-- ALL columns mutable in-run but absent from fingerprint + boot reset + reset_fleet —
-- owning_sim_run_id first; the first pair after ANY non-cert session on the depot is the
-- reproduction instrument.
--
-- ── THE INSTRUMENT (re-runnable verbatim) ──────────────────────────────────────────────────
-- One arm (repeat per arm; cert_harness is exempt from the metronome and the governor):
--
--   DO $arm$
--   DECLARE v_run uuid; v_t0 timestamptz := clock_timestamp(); v_clock timestamptz; v_status text;
--   BEGIN
--     PERFORM public.ottoq_tick_invariance_reset_fleet('11111111-1111-1111-1111-111111111111'::uuid, 424242);
--     v_run := twin.ottoq_sim_start_run('busy_day', '2026-09-01 02:00:00+00'::timestamptz, 60, 424242, 'cert_harness');
--     BEGIN PERFORM twin.ottoq_sim_prime_deployment(v_run, '2026-09-01 02:00:00+00'::timestamptz, 0.70);
--     EXCEPTION WHEN OTHERS THEN RAISE WARNING 'prime failed: %', SQLERRM; END;
--     LOOP
--       SELECT sim_clock_current, status INTO v_clock, v_status FROM public.ottoq_sim_runs WHERE sim_run_id=v_run;
--       EXIT WHEN v_status <> 'running' OR v_clock >= '2026-09-01 08:00:00+00'::timestamptz;
--       EXIT WHEN EXTRACT(EPOCH FROM (clock_timestamp()-v_t0)) >= 90;  -- pair-14 rule: ONE transaction per arm; a resumed arm shifts now() and the real-domain TTLs with it
--       PERFORM public.ottoq_sim_advance_tick(v_run);
--     END LOOP;
--   END $arm$;
--   -- then run the projection below, then: SELECT ottoq_sim_stop_and_reset(<run>, 'determinism_arm_complete');
--
-- Stream projection for one run (replace :run). Volatile identifiers (booking/leg/event UUIDs,
-- wall-clock created_at) are deliberately excluded; vehicle/stall ids are stable fleet rows.
-- ============================================================================================

WITH r AS (SELECT :run::uuid AS id)
SELECT
  (SELECT md5(COALESCE(string_agg(
      issued_at::text||'|'||vehicle_id::text||'|'||command_type||'|'||COALESCE(payload->>'stall_id','-')||'|'||status||'|'||COALESCE(reason_code,'-'),
      E'\n' ORDER BY issued_at, vehicle_id, command_type, COALESCE(payload->>'stall_id','-'), status), ''))
     FROM public.ottoq_vehicle_commands c, r WHERE c.sim_run_id=r.id) AS h_cmd,
  (SELECT md5(COALESCE(string_agg(
      sim_clock::text||'|'||tick_seq::text||'|'||action_context||'|'||entity_id::text||'|'||outcome_status
      ||'|'||COALESCE(enacted_action->>'verb', proposed_action->>'verb','-')||'|'||COALESCE(proposed_action->>'stall_id','-'),
      E'\n' ORDER BY sim_clock, tick_seq, action_context, entity_id, outcome_status,
                    COALESCE(enacted_action->>'verb', proposed_action->>'verb','-'), COALESCE(proposed_action->>'stall_id','-')), ''))
     FROM public.ottoq_decisions d, r WHERE d.sim_run_id=r.id) AS h_dec,
  (SELECT md5(COALESCE(string_agg(
      event_type||'|'||CASE WHEN e.entity_type IN ('ocpp_session','service_detail_record','sim_run')
                            THEN '-'   -- per-run random ids (pairs 9-10 finding); vehicle/stall/depot ids are stable
                            ELSE COALESCE(entity_id::text,'-') END,
      E'\n' ORDER BY event_type,
                    CASE WHEN e.entity_type IN ('ocpp_session','service_detail_record','sim_run')
                         THEN '-' ELSE COALESCE(entity_id::text,'-') END), ''))
     FROM public.ottoq_events e, r WHERE e.sim_run_id=r.id) AS h_evt,
  (SELECT md5(COALESCE(string_agg(
      lower(during)::text||'|'||upper(during)::text||'|'||vehicle_id::text||'|'||stall_id::text||'|'||purpose||'|'||state,
      E'\n' ORDER BY lower(during), vehicle_id, stall_id, purpose, state), ''))
     FROM public.ottoq_stall_bookings k, r WHERE k.sim_run_id=r.id) AS h_bkg,
  public.ottoq_tick_invariance_metrics((SELECT id FROM r)) AS metrics;
