-- db/checks/0159 — G42
-- A FAITHFUL REPLAY WOULD DOUBLE-COUNT THE PROPOSERS THAT REGENERATE
--
-- Found 2026-09-08 23:0x CT (2026-09-09 04:0x UTC) while building Posture A,
-- by asking a question the Posture-B proof never had to answer: what happens
-- when you capture a REAL run instead of a hand-written one.
--
-- db/checks/0157 proved Posture B with a SYNTHETIC stream and said so. This is
-- the thing that synthesis was hiding.
--
-- ===========================================================================
-- 1. THREE WRITERS, AND ONLY ONE OF THEM STAMPS A TICK
-- ===========================================================================
-- Measured: exactly three functions INSERT into ottoq_external_proposals.
--
--   public.ottoq_l2_optimize_assignments  direct insert, INSIDE the certified
--                                         tick. No tick_seq -- 0236 stamped the
--                                         door and deliberately left this alone.
--   public.ottoq_submit_external_proposal  the agent door. Stamps tick_seq (0236).
--   public.ottoq_proposal_replay_inject    replay. Carries the recorded tick_seq.
--
-- And the traffic splits along that seam, hard:
--
--   source                   total   via door   direct   post-0236 w/ tick   w/o
--   ----------------------  ------   --------   ------   -----------------  ----
--   greedy_constrained      12,458          0   12,458                   0     2
--   ottoq_service_priority   1,918        385    1,533                   8     0
--
-- So the LARGEST proposer in the system -- greedy_constrained, 12,458 proposals
-- -- can never carry a tick_seq, because it is written by
-- ottoq_l2_optimize_assignments and 0236 only reached the door. That is not new
-- and it is not an accident; 0236's header states it and gives a good reason:
--
--     "Posture B replays the EXTERNAL stream. Internal deterministic proposers
--      do not need replaying -- they regenerate themselves identically from the
--      same seed, which is what 'deterministic internal proposer' means."
--
-- Correct. But it has a consequence 0236 did not have to think about, because
-- 0237 and 0239 did not exist yet.
--
-- ===========================================================================
-- 2. THE CONSEQUENCE: CAPTURE TAKES EVERYTHING, INCLUDING WHAT REGENERATES
-- ===========================================================================
-- public.ottoq_proposal_replay_capture(p_sim_run_id, p_replay_id, p_sources):
--
--     WHERE p.sim_run_id = p_sim_run_id
--       AND (p_sources IS NULL OR p.source = ANY (p_sources))
--
-- p_sources DEFAULTS TO NULL, and NULL means EVERY SOURCE. So the default
-- behaviour of "record this run's agent stream" is to record the internal
-- deterministic proposers too.
--
-- Replay that into ottoq_determinism_pair_replay and both things happen:
--
--   (a) the recorded greedy_constrained / ottoq_service_priority rows are
--       INJECTED -- at tick -1, because capture stores COALESCE(tick_seq,-1)
--       and those rows have no tick; and
--   (b) ottoq_l2_optimize_assignments and ottoq_service_priority_propose run
--       during the replayed arm and REGENERATE the same proposals at their real
--       ticks, exactly as 0236 says they will.
--
-- The same logical proposal is then present TWICE, from two mechanisms, at two
-- different ticks. h_prop hashes both. The replay is not the recording; it is
-- the recording plus a ghost of itself.
--
-- Worse than a wrong number: the ghosts land at tick -1, i.e. before tick 1, so
-- they are visible to the decide path for the WHOLE run and can be selected in
-- preference to the real ones. A replay could change the decisions it was
-- supposed to reproduce.
--
-- ===========================================================================
-- 3. WHY 0157 DID NOT CATCH IT, STATED PLAINLY
-- ===========================================================================
-- Because the stream in 0157 was hand-written: 24 rows, all source
-- 'agent_probe', a source nothing regenerates. Every hash matched, the negative
-- controls fired correctly, and the proof is sound FOR WHAT IT CLAIMED. It
-- claimed the disposer is deterministic given a stream. It did not claim, and
-- could not have caught, that capture picks up more than it should.
--
-- 0157's own "what is still owed" list opens with "a REAL captured stream".
-- This is why that item was first.
--
-- ===========================================================================
-- 4. THE FIX, AND WHY 0241's REGISTRY IS EXACTLY THE RIGHT MECHANISM
-- ===========================================================================
-- What must be excluded from a capture is precisely "the proposers that
-- regenerate deterministically from the seed" -- and 0241 built a table naming
-- exactly those, for exactly that reason, from measurement:
-- ottoq_certified_proposers holds greedy_constrained, ottoq_service_priority
-- and cuopt.
--
-- So (migration 0242, after 0241):
--
--   * ottoq_proposal_replay_capture EXCLUDES registered proposers by default.
--     A caller who genuinely wants them names them in p_sources explicitly --
--     the dangerous thing stops being the default and becomes a deliberate act.
--   * The replay row count is recorded so a capture that took nothing is
--     visibly different from a capture that was never run.
--
-- ===========================================================================
-- 5. THE PREDICTION, WRITTEN BEFORE THE EXPERIMENT
-- ===========================================================================
-- Recorded now, in advance, so it can be wrong. The next step already scheduled
-- is: run a real non-cert benchmark run with the internal proposers live, then
-- capture and replay it.
--
--   P1. Captured with today's default (p_sources NULL), the replay will contain
--       greedy_constrained and/or ottoq_service_priority rows, all at tick -1.
--   P2. Replayed into a pair, arm A's ottoq_external_proposals will hold MORE
--       rows for those sources than the source run did -- the injected copies
--       plus the regenerated ones.
--   P3. Both arms will still AGREE (the pair will pass), because both arms are
--       ghosted identically. That is the dangerous part: the defect does not
--       announce itself as a failure. It announces itself as a number that is
--       quietly too big.
--
-- If P3 is wrong and the pair FAILS, the defect is worse than described, not
-- better -- it would mean the doubled stream is also nondeterministic.

-- ===========================================================================
-- 6. THE EXPERIMENT, RUN 2026-09-09 00:2x CT (05:2x UTC)
-- ===========================================================================
-- Setup, and one thing found while doing it that matters more than the setup:
--
-- To generate a REAL stream the run must be non-cert, which opens
-- ottoq_cron_tick's gate to ottoq-orchestrate-tick and therefore to NVIDIA. The
-- plan was to shut that with a depot-scoped cuopt_propose_enabled=0. On writing
-- it, the resolution order turned out to already answer the question:
-- ottoq_policy_get resolves run -> depot -> GLOBAL -> default, and there has
-- been a GLOBAL row since 0152:
--
--   scope_type global, param cuopt_propose_enabled, value 0, by 0152_deterministic_only
--
-- So line 24's `default 1` is never reached. The orchestrate dispatch has been
-- shut globally since 0152, for every run, not just certifications.
--
-- THAT IS A THIRD LEG UNDER db/checks/0158's CONCLUSION, and a better one than
-- either of the first two. 0158 argued "the endpoint has not been called since
-- 2026-08-30" from (a) the ledger, which was blind to two doors, and (b) cron
-- durations, which are circumstantial and get pruned. This is a standing
-- configuration row that closes the unattended door outright. 0158's verdict is
-- unchanged; its evidence is now much stronger than when it was written.
--
-- (The depot-scoped rows for the Benchmark depot were written anyway and kept.
-- They are correct standing policy for a benchmark depot regardless of what the
-- global tier happens to say, and they do not depend on it.)
--
-- ---------------------------------------------------------------------------
-- THE REAL STREAM
-- ---------------------------------------------------------------------------
--   ottoq_cert_arm(seed 159001, otto_q, 8 ticks, Benchmark depot 22222222-...)
--   -> run 70733335-639c-47f0-84ce-c24c64cdec0c
--      8 ticks, 618 decisions, 7 external proposals
--      sources: greedy_constrained, ottoq_service_priority
--
-- Not synthetic. Written by the engine's own proposers during a real tick loop.
--
-- ---------------------------------------------------------------------------
-- P1 -- CONFIRMED, AND THE PREDICTION WAS PARTLY WRONG
-- ---------------------------------------------------------------------------
-- P1 said: "Captured with today's default (p_sources NULL), the replay will
-- contain greedy_constrained and/or ottoq_service_priority rows, ALL AT TICK -1."
--
-- Measured, capturing the same run twice -- once reproducing the OLD default by
-- naming the registered proposers explicitly, once with 0242's new default:
--
--   OLD default (every source)   7 rows      <- the defect
--   NEW default (0242)           0 rows      <- the fix
--
-- and the old-style capture splits:
--
--   tick_seq   rows   source
--   --------   ----   ----------------------
--        -1       6   greedy_constrained
--         2       1   ottoq_service_priority
--
-- The main claim holds: 6 of 7 land in the -1 bucket, exactly as predicted, and
-- 0242's default correctly records none of them.
--
-- **"ALL at tick -1" was too strong.** The one ottoq_service_priority row carries
-- a REAL tick, because that proposal came through the agent door, which 0236
-- stamps -- while greedy_constrained is written directly by
-- ottoq_l2_optimize_assignments, which 0236 deliberately left alone.
--
-- That is the two-write-paths inconsistency 0241 recorded and declined to fix,
-- showing up as a measurement: ONE PROPOSER'S OUTPUT SPLITS ACROSS TWO TICK
-- DOMAINS DEPENDING ON WHICH WRITE PATH IT TOOK. A replay of a mixed stream
-- would therefore have put some rows back at their real tick and the rest at
-- -1 -- a worse failure than the uniform one predicted, because it looks
-- partially correct.
