-- ===========================================================================
-- 0160  G43 -- A REPLAYED PROPOSAL MOVES THE EVENT STREAM OF ONE ARM ONLY
-- ===========================================================================
-- Opened 2026-09-09 ~00:35 AM CT (05:35 UTC) out of 0159 section 7.
--
-- WHAT HAPPENED
--
-- The Posture B replay pair on the flagship column busy_day / 314159 / 12t
-- FAILED, and failed in a shape nothing in the harness has produced before:
-- exactly one atom moved, h_evt, and it moved on ONE ARM.
--
--   arm A (d06abdc4-3455-47a7-acd5-680d8c8bd98c)  h_evt 6cd5031317939de6d83bc1a3888b4ea1
--   arm B (3a224796-177e-48e3-bd1c-d9165f23aa21)  h_evt 9c631343c32cca7a861b17bc5bc8f4b7
--
-- Arm B's value IS the canon. Both arms of the no-replay pair at 03:42 today
-- (54b1c04a / ff826272) and both arms at 20:50 yesterday (bd2de131 / 8291f536)
-- produced 9c631343... So arm B ran a canonical run; arm A did not.
--
-- Every other atom agreed, including the two that would carry a changed
-- decision: h_dec was identical on both arms AND identical to the no-replay
-- canon, and h_bkg, h_nrg, h_rule, h_sdr, h_rcl, endst all matched. So arm A
-- emitted a different EVENT STREAM while taking the same decisions, booking the
-- same stalls, issuing the same energy commands and ending in the same state.
--
-- WHY THE POST-HOC TABLE READ CANNOT JUDGE THIS
--
-- Reading ottoq_events afterwards shows arm A holding 4,656 rows against arm B's
-- 4,531, +116 of them at the final sim clock -- one per vehicle. That difference
-- is REAL but it is not the finding, and it would be a false lead to treat it as
-- one. The pair's own structure explains it:
--
--   FOR v_arm IN 1..2 LOOP
--     ottoq_tick_invariance_reset_fleet(...)   <-- line 56, top of each arm
--     ... run the tick loop ...
--     build the arm object, h_evt included     <-- line 98-155, HASH TAKEN HERE
--     ottoq_sim_stop_and_reset(v_run, ...)     <-- line 160, AFTER the hash
--   END LOOP;
--
-- Arm A's teardown and arm B's fleet reset both write events after arm A's hash
-- was taken, and the payloads confirm it -- they carry last_state_change moving
-- to the transaction wall clock and then back to the sim start, with
-- condition_drawn_run set to arm A. All four runs (both replay arms AND both
-- control arms) recompute to values other than their own verdict for this
-- reason. Only the hash the pair took inside its own transaction is evidence.
--
-- THE TWO CONTROLS, AND THE PREDICTIONS, WRITTEN BEFORE EITHER RAN
--
-- C1 -- ottoq_determinism_pair_replay on the same column with p_replay_id NULL.
--       Asks: is this the replay, or is it 0239's derivation of the pair?
--
--       PREDICTION: C1 PASSES, both arms 9c631343... I expect this because
--       every behavioural addition 0239 made is inside IF p_replay_id IS NOT
--       NULL, and check 0157's P0 control (this same function, replay NULL)
--       already passed. Confidence moderate, not high: 0157 ran on the 4-vehicle
--       grid fixture, which is small enough to miss a whole class of thing.
--       If C1 FAILS, the finding is not about replay at all -- it is that 0239
--       shipped a defective certification function, and 0157's Posture B proof
--       has to be re-read in that light.
--
-- C2 -- the identical replay pair, run again.
--       Asks: is the divergence deterministic, or is it a coin?
--
--       PREDICTION: C2 FAILS AGAIN with arm A at exactly 6cd50313... and arm B
--       at 9c631343... A coin would be worse news and a different investigation;
--       a repeatable arm-A-only divergence is a mechanism, and mechanisms can be
--       found. Confidence moderate. If arm A lands on a THIRD value, the replay
--       path is nondeterministic in itself and Posture B is not safe to promote.
--
-- Both controls are scheduled through pg_cron rather than run from a client
-- session, for the reason the rounds are: the 25-minute statement timeout and
-- an execution that does not depend on a connection staying up.
--
-- Round 31 finished at 04:58 (r31_f) and no cert job is scheduled after it, so
-- both controls run alone on the flagship depot.

-- ===========================================================================
-- 2. THE MECHANISM, FOUND BEFORE THE CONTROLS FINISHED -- AND IT IS NOT REPLAY
-- ===========================================================================
--
-- The clean comparison is arm A of the replay pair against arm A of the
-- no-replay pair on the same column. Both are FIRST arms, so both carry the
-- identical post-hash contamination described above, and it cancels. Done that
-- way, the entire in-run divergence is NINE EVENTS AT ONE SIM CLOCK:
--
--   sim_clock_at           event_type             replay armA   no-replay armA
--   --------------------   --------------------   -----------   --------------
--   2026-09-01 06:30:00    stall.state_changed              2                0
--   2026-09-01 06:30:00    vehicle.state_changed            7                0
--
-- and NOTHING anywhere else, at any other clock. The +116 at 08:00 is present
-- in both and cancels exactly, which is what confirms it was contamination.
--
-- 06:30 is tick 10 of 12 (02:00 + 9 x 30 min).
--
-- THE NINE PAYLOADS NAME THE CAUSE. Every one of them is a clearing diff:
--
--   {"diff": {"updated_at":              {"to": "2026-09-09T05:24:00.957086+00",
--                                        "from": "2026-09-09T05:22:18.994724+00"},
--             "robotic_tether_phase":    {"to": null, "from": "unstow"},
--             "robotic_tether_until":    {"to": null, "from": "2026-09-01T06:00:18.5+00"},
--             "robotic_tether_stall_id": {"to": null, "from": "7361..."}}}
--
--   {"diff": {"status":             {"to": "available", "from": "occupied"},
--             "current_vehicle_id": {"to": null, "from": "36ff94e5-..."}}}
--
-- Read the "from" on updated_at: 2026-09-09 05:22:18.994724 -- a WALL CLOCK
-- timestamp from 102 seconds BEFORE this pair's transaction began at
-- 05:24:00.957086. Those rows were carrying robotic-tether state written by
-- something that ran before the pair. They survived the boot. They survived nine
-- ticks. At tick 10 the tether deadline (sim 06:00:18.5) came due, the engine
-- cleared them, and nine events were emitted that the canonical run does not
-- emit.
--
-- Arm B never had them, because arm A had already cleared them.
--
-- WHY THE RESET DOES NOT SAVE IT -- read from the catalog, not inferred:
--
--   SELECT pg_get_functiondef(oid) ILIKE '%robotic_tether%'
--     FROM pg_proc WHERE proname IN
--          ('ottoq_tick_invariance_reset_fleet','ottoq_sim_stop_and_reset');
--
--   ottoq_tick_invariance_reset_fleet(uuid,bigint,timestamptz)   false
--   ottoq_sim_stop_and_reset(uuid,text)                          false
--
-- NEITHER FUNCTION MENTIONS robotic_tether AT ALL. The per-arm fleet reset does
-- not clear it and the run teardown does not clear it. So any robotic-tether
-- state live in the world when a pair starts is inherited by ARM A ONLY, and
-- arm B always boots from the world arm A left.
--
-- THIS IS NOT ABOUT REPLAY. Nothing in the mechanism involves a proposal, an
-- injection, or 0239. The replay pair is simply the pair that happened to start
-- 102 seconds after something left tether state on seven flagship vehicles.
--
-- SO THE STATED PREDICTIONS FOR C1 AND C2 ARE NOW CONFOUNDED, AND SAYING SO IS
-- THE POINT OF HAVING WRITTEN THEM DOWN. Arm A of the 05:24 pair CONSUMED the
-- residue. Measured immediately after, on the flagship depot:
--
--   vehicles with robotic_tether_phase / _until / _stall_id    0 / 0 / 0
--   max(updated_at)                     2026-09-09 05:24:00.957086  (the pair)
--
-- The world is clean. C1 and C2 therefore both run on a clean world and are
-- both expected to PASS -- and a C1 pass CANNOT exonerate replay, because the
-- condition that produced the failure is gone. My C1 prediction ("C1 passes,
-- therefore replay is the cause") was the right experiment to schedule and the
-- WRONG INFERENCE TO HANG ON IT. They are kept and judged as run, but the
-- decisive test is a third one.
--
-- C3 -- PLANT THE RESIDUE, RUN THE ORIGINAL PAIR WITH NO REPLAY AT ALL
--
--   UPDATE public.vehicles SET robotic_tether_phase='unstow',
--          robotic_tether_direction='mate',
--          robotic_tether_until='2026-09-01 06:00:18.5+00',
--          robotic_tether_stall_id=<a flagship stall>
--    WHERE id IN (<7 flagship vehicles>);
--   SELECT public.ottoq_determinism_pair(314159, 12, 'busy_day', <flagship>,
--                                        '2026-09-01 02:00:00+00', 900);
--
-- ottoq_determinism_pair, not the replay function. No p_replay_id anywhere.
-- Planting and pair are in ONE cron job so nothing can run between them.
--
--   PREDICTION: C3 FAILS on h_evt, arm A only, with arm B landing on the canon
--   9c631343... I hold this with high confidence, because the mechanism is not
--   inferred from the failure -- it is read out of the two reset functions,
--   which demonstrably do not touch these columns.
--
--   If C3 PASSES, tether residue alone is not sufficient, the replay is back in
--   the frame, and this section is wrong and must be rewritten rather than
--   patched.
--
-- WHAT THIS MEANS IF C3 CONFIRMS, STATED PLAINLY
--
-- The six green certification columns have been green partly by luck. A pair
-- fails whenever the world happens to carry live robotic-tether state at the
-- moment it starts, and passes when it does not, and nothing in the harness
-- distinguishes the two. That is not a replay defect and not an agent-layer
-- defect. It is a determinism defect in the certification itself, and it is the
-- sharp form of G26 -- "production and the proof harness share one database" --
-- because the residue is left by whatever touched the depot last.
--
-- It also means the arms are NOT booted from the same world, which is the one
-- property the whole pair rig assumes. Every canon recorded to date was taken
-- under an assumption that is only usually true.

-- ===========================================================================
-- 3. THE BLIND-SPOT INVENTORY -- HOW MANY MORE OF THESE ARE THERE
-- ===========================================================================
--
-- Once the mechanism is "a mutable column that the reset does not clear and the
-- boot fingerprint cannot see", the obvious question is how many such columns
-- exist. Enumerated from the catalog:
--
--   SELECT c.table_name, c.column_name
--     FROM information_schema.columns c, defs d
--    WHERE c.table_name IN ('vehicles','stalls')
--      AND pg_get_functiondef(ottoq_tick_invariance_reset_fleet) NOT LIKE '%'||c.column_name||'%'
--      AND pg_get_functiondef(ottoq_boot_state_fingerprint)      NOT LIKE '%'||c.column_name||'%';
--
--   -> 49 columns (26 on vehicles, 23 on stalls)
--
-- THE TEST IS TEXTUAL AND ITS ASYMMETRY IS THE WHOLE POINT: a column name
-- appearing in a function body does NOT prove the function resets or hashes it.
-- A column name being ABSENT from both bodies DOES prove neither can. So this
-- list is sound as an upper bound on what is covered and a hard lower bound on
-- what is not. Every one of these 49 is provably invisible to both.
--
-- Most of the 49 are harmless because they are STATIC -- identity and geometry
-- that no tick ever writes: make, model, vin, year, color, license_plate,
-- battery_capacity_kwh, stall_width_ft, absolute_lat/lng, fiducial_marker_id,
-- uwb_beacon_id, and so on. A column a run never writes cannot carry residue
-- between arms.
--
-- The dangerous subset is the MUTABLE ones, and it is short enough to name:
--
--   vehicles.robotic_tether_phase       <-- CONVICTED, this pair
--   vehicles.robotic_tether_until       <-- CONVICTED, this pair
--   vehicles.robotic_tether_stall_id    <-- CONVICTED, this pair
--   vehicles.robotic_tether_direction   <-- same family, same exposure
--   vehicles.current_depot_id
--   vehicles.owning_sim_run_id
--   vehicles.is_active
--   stalls.reserved_for_mission_id
--   stalls.staging_role
--
--   vehicles.current_soc_updated_at     <-- NOT a defect. This is 0137's column,
--                                           deliberately outside the fingerprint
--                                           because it is a write timestamp.
--                                           Excluding it is the fix, not the bug.
--
-- So the tether family is four columns of a nine-column mutable blind spot, and
-- the fix is tractable rather than whack-a-mole. It is NOT enough to clear the
-- four that were convicted: the same coin can be flipped by any of the others.
--
-- THE FIX HAS TO BE BOTH HALVES, IN THIS ORDER, PER THE BLIND-SPOT PROMOTION
-- DOCTRINE (CLAUDE.md 2.9a):
--
--   1. WIDEN THE BOOT FINGERPRINT first, MEASURED. If fp had covered these
--      columns, this pair would have failed at 'fp' saying "the two arms did not
--      boot from the same world" -- which is true, actionable, and immediate --
--      instead of failing at h_evt nine ticks later with no indication why.
--      The harness must be able to SEE an unequal boot before anyone tries to
--      guarantee an equal one.
--
--   2. THEN MAKE THE RESET TOTAL for the mutable set, so the boot is actually
--      equal and fp can be promoted to ENFORCED.
--
-- Doing (2) without (1) would close this instance and leave the class invisible,
-- which is the mistake that let V7's residue sweep (task #40) miss these four in
-- the first place. This finding is that sweep's escapee, and the lesson is that
-- a residue sweep driven by reading code misses what a sweep driven by the
-- catalog does not.

-- ===========================================================================
-- 4. C1 JUDGED, AND THE BOOT FINGERPRINT IS BLIND TO THE FLEET
-- ===========================================================================
--
-- C1 (same column, ottoq_determinism_pair_replay, p_replay_id NULL), fired
-- 05:40:00 UTC, ran alone (pg_stat_activity confirmed; cron.job_run_details
-- reported "succeeded / SET" after 1 s, which is the known two-statement-job
-- artefact and NOT a completion):
--
--   status  passed
--   arm A   h_evt 9c631343c32cca7a861b17bc5bc8f4b7
--   arm B   h_evt 9c631343c32cca7a861b17bc5bc8f4b7   <- both on the canon
--
-- The C1 prediction is CONFIRMED as written. It also confirms nothing about
-- replay, exactly as section 2 said in advance: the world was already clean, so
-- a pass was the expected outcome under BOTH hypotheses. C1's real value is
-- narrower and still worth having -- it rules out the possibility that 0239
-- shipped a pair function that is broken on every run, which was the other thing
-- worth being afraid of. The replay-vs-residue question is C3's.
--
-- ---------------------------------------------------------------------------
-- AND NOW THE PART THAT MAKES THIS A HARNESS FINDING RATHER THAN A BUG REPORT
-- ---------------------------------------------------------------------------
--
-- The pair already computes a boot fingerprint per arm, at line 68, and stores
-- it in the verdict as arm_a.boot / arm_b.boot. On the pair that FAILED:
--
--   SELECT arm_a->'boot' = arm_b->'boot' ...
--
--   3a224796 (the failed replay pair)   boot_equal = TRUE
--   54b1c04a (the passing control)      boot_equal = TRUE
--
-- The two arms of the failed pair booted from provably different fleet states --
-- seven vehicles carried live tether state in arm A and none in arm B -- and the
-- boot fingerprint reported them IDENTICAL.
--
-- Reading ottoq_boot_state_fingerprint(uuid,uuid) explains why. It hashes six
-- things: visit_needs, stall_bookings, itinerary_legs, vehicle_dispatches,
-- ocpp_chargers, calibration. public.vehicles and public.stalls appear in its
-- body ONLY inside EXISTS(...) subqueries used to scope the other tables to the
-- depot. Neither table is ever hashed.
--
--   THE BOOT STATE FINGERPRINT DOES NOT INCLUDE THE ASSETS OR THE SERVICE
--   POINTS. It hashes everything ABOUT them -- their bookings, their needs,
--   their legs, their dispatches, their chargers -- and not them.
--
-- Two consequences, and the second is worse than the first:
--
--   (a) 'boot' is not in the pair's equality list at all. The list is fp, h_cmd,
--       h_dec, h_evt, h_bkg, h_nrg, h_prop, h_defr, h_cal, h_rule, h_rcl, h_sdr,
--       ticks, endst -- fourteen atoms, and 'boot' is not one of them. The pair
--       records both arms' boot state and never compares them.
--
--   (b) Even if it did compare them, it would not have caught this, because the
--       fingerprint is blind to the columns that differed. Promoting 'boot' to
--       the equality list as it stands would be G25's defect again -- enforcing
--       a comparison narrower than the property being claimed.
--
-- So the fix is NOT "add boot to the equality list". It is: widen first, so
-- there is something worth comparing, and only then enforce.
--
-- WHY NOT SIMPLY WIDEN ottoq_boot_state_fingerprint ITSELF: because the same
-- function computes 'endst', which IS enforced. Widening it moves endst for
-- every column, forces a full recert, and invalidates all six canons in one
-- migration -- to fix a defect whose blast radius is not yet measured. That is
-- the wrong order.
--
-- THE SHAPE OF THE FIX, then, is a separate boot-time fleet fingerprint added as
-- a MEASURED atom, disturbing no existing canon (forces_recert FALSE), promoted
-- to ENFORCED only after a flagship round shows the arms agree on it -- which is
-- precisely the doctrine CLAUDE.md 2.9a lays down and precisely what 0139, 0206,
-- 0217 and 0225 each did. It is drafted only after C3 reports.

-- ===========================================================================
-- 5. THE SHARP FORM: fp IS THE BOOT WORLD FINGERPRINT, IT IS ENFORCED, AND IT
--    WAS EQUAL
-- ===========================================================================
--
-- Section 4 proposed adding a NEW boot-time fleet fingerprint as a measured
-- atom. That was the wrong fix and it is withdrawn: the certification already
-- has exactly that atom, it is already enforced, and the defect is that it is
-- too narrow. Extending what exists is the job; adding a parallel instrument
-- beside it would have been the "rebuild what exists" failure CLAUDE.md rule 5
-- names.
--
--   'fp' in the arm object is r.payload->>'world_fingerprint'
--   written by twin.ottoq_sim_start_run(...) and public.ottoq_run_boot_draw(uuid)
--   -- both at RUN START.
--
-- So fp is the start-of-run world hash. Its whole purpose is the sentence "both
-- arms began from the same world." It is one of the fourteen ENFORCED atoms.
--
--   On the pair that failed:  fp arm A = fp arm B = 803698f332adc0d06cbefca79dad1ce0
--
-- The worlds were not the same. Seven vehicles carried live robotic-tether state
-- in arm A and none in arm B, and the atom that exists to detect precisely that
-- reported them identical.
--
-- WHY, from ottoq.ottoq_world_fingerprint(uuid) -- it is an ENUMERATED column
-- list, not a row image:
--
--   vehicles (WHERE home_depot_id = p_depot AND category='autonomous'; 116 rows):
--       id, current_soc, current_state, current_stall_id, current_soc_source,
--       target_soc, config - 'condition_drawn_run', last_state_change
--   stalls:  id, status, current_vehicle_id, reserved_by, reserved_at,
--            reservation_expires_at
--   plus ocpp chargers, vehicle_need_profile, and the BESS units.
--
--   robotic_tether_phase, robotic_tether_until, robotic_tether_stall_id and
--   robotic_tether_direction are NOT in that list.
--
-- A vehicle mid-tether is, by any reading, start-relevant world state: it has a
-- deadline (robotic_tether_until) that will come due during the run and change
-- what the engine does. It belongs in this hash.
--
-- AND THE FUNCTION ITSELF SAYS SO. Its own header comment reads:
--
--   "The start-relevant world, hashed. ... Extend the column set only alongside
--    the 0046 probe that justifies it."
--
-- Every prior extension followed that rule and left its probe number in the
-- body: 0115 added the pair-17 columns, 0137 REMOVED current_soc_updated_at as
-- a write timestamp, 0107 added the needs profile, 0133 added the BESS after
-- 0051 showed peak_site_kw differing between two byte-identical arms because
-- the battery carried across runs, 0135 added its temperature.
--
-- 0160 is the next such probe, and the tether columns are the next such
-- extension. The mechanism is identical to 0133's, one table over: state that
-- carries across runs, that the fingerprint cannot see, that changes the run.
--
-- ---------------------------------------------------------------------------
-- WHAT THE FIX COSTS, STATED BEFORE IT IS BUILT
-- ---------------------------------------------------------------------------
--
-- Extending ottoq_world_fingerprint moves fp for EVERY column. fp is enforced,
-- so every canon in the matrix is invalidated and the migration is
-- forces_recert TRUE. That is not a reason to avoid it -- it is exactly what
-- forces_recert exists for (0192): an atom that was wrong must move, and a
-- canon derived from a wrong atom must not survive the correction. 0133 paid
-- the same price for the same reason.
--
-- THE ORDER MATTERS AND IS NOT NEGOTIABLE. Widening fp while the reset still
-- leaves tether residue would make pairs fail whenever residue happens to be
-- present -- correctly, but intermittently, which is the worst of both worlds
-- for diagnosis. So ONE migration does BOTH halves:
--
--   (a) ottoq_tick_invariance_reset_fleet clears the tether family for the
--       depot's fleet, so the two arms genuinely start equal; and
--   (b) ottoq_world_fingerprint hashes the tether family, so that when they do
--       not start equal the pair says so at fp, on tick zero, instead of at
--       h_evt nine ticks later with no indication why.
--
-- (a) without (b) closes this instance and leaves the class invisible. (b)
-- without (a) is an intermittent alarm. Both together is the fix.
--
-- THE OTHER MUTABLE COLUMNS ARE ASSESSED, NOT SWEPT IN. From section 3's nine:
--   current_depot_id, is_active, stalls.reserved_for_mission_id,
--   stalls.staging_role  -- candidates on the same argument, but no probe has
--                            convicted them; adding them on suspicion is how a
--                            fingerprint accretes noise it cannot justify, and
--                            the function's own comment forbids it.
--   owning_sim_run_id     -- MUST NOT be hashed: it holds each arm's own run id
--                            and differs between arms BY DESIGN.
--   current_soc_updated_at -- already correctly excluded by 0137.
--
-- Nothing is applied until C3 reports.
